import 'package:flutter/material.dart';

class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  static String normalizeCode(String lang) {
    final l = lang.toLowerCase().trim();
    if (l == 'hi' || l == 'hindi') return 'hi';
    if (l == 'pa' || l == 'punjabi') return 'pa';
    if (l == 'bn' || l == 'bengali') return 'bn';
    if (l == 'hr' || l == 'haryanvi') return 'hr';
    if (l == 'hinglish' || l == 'hing' || l == 'romanized' || l.contains('hinglish')) return 'hinglish';
    return 'en';
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'field_crop_summary': 'Field & Crop Health Summary',
      'satellite_weather_favorable': 'Satellite radar & water index in safe zone.',
      'radar_backscatter': 'SAR Backscatter',
      'confidence_short': 'confidence',
      'field_map': 'Field Map',
      'farm_map_instruction': 'Draw boundary, search coordinates, or use GPS location',
      'processing_radar_weather': 'Processing radar & weather telemetry...',
      'irrigation_decision_footnote': 'Calculated directly from active weather, evapotranspiration, and Sentinel-1 SAR readings.',
      'feedback_title': 'Help us improve NabhKrishi',
      'feedback_subtitle': 'How useful are our irrigation & crop recommendations?',
      'farmer_feedback_form': 'Farmer Feedback',
      'comments_hint': 'Share your experience, feature requests, or suggestions...',
      'submitting': 'Submitting...',
      'feedback_thanks': 'Thank you! Your feedback helps us improve NabhKrishi for all farmers.',
      'welcome_title': 'Welcome to NabhKrishi',
      'reset_password': 'Reset Password',
      'welcome_subtitle': 'Your farm. Your future. Smarter.',
      'join_subtitle': 'Fill the details to join NabhKrishi.',
      'reset_subtitle': 'Enter your email to receive a password reset link.',
      'trace_boundary_instruction': 'Trace around your farm boundary',
      'confirm_farm': 'Confirm Farm',
      'boundary_confirmed': 'Farm Boundary Confirmed',
      'edit': 'Edit',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'locate_farm': 'Locate Farm Coordinates',
      'insights_analytics': 'Insights & Field Analytics',
      'insights_subtitle': 'Irrigation recommendations and moisture history',
      'filter_7d': '7 Days',
      'filter_30d': '30 Days',
      'filter_all': 'All Time',
      'field_label': 'Field',
      'use_my_location': 'Use My Location',
      'select_farm_area': 'Select Farm Area',
      'draw_instruction': 'Tap on the map to draw your farm boundary.',
      'clear_boundary': 'Clear Area',
      'confirm_location': 'Confirm Farm Area',
      'confirm_farm_location': 'Confirm Farm Location',
      'weather_section': 'Weather Condition',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'rainfall_7d': 'Rainfall (7 Days)',
      'rainfall_14d': 'Rainfall (14 Days)',
      'et0_7d': 'ET0 (Water Demand)',
      'deficit_7d': 'Water Deficit',
      'field_condition': 'Soil / Field Condition',
      'estimated_water_condition': 'Estimated Field Water Condition',
      'low_stress': 'Low estimated water stress',
      'moderate_requirement': 'Moderate water requirement',
      'high_deficit': 'High estimated water deficit',
      'satellite_section': 'Sentinel-1 Satellite Information',
      'vv_mean': 'VV Mean',
      'vv_change': 'VV Change',
      'observation_age': 'Latest Observation Age',
      'satellite_freshness': 'Satellite data was updated {days} days ago.',
      'more_details': 'More Details',
      'irrigation_recommendation': 'Irrigation Recommendation',
      'apply_irrigation': 'Apply {amount} mm irrigation',
      'no_irrigation': 'No irrigation required',
      'explanation_title': 'Why this recommendation?',
      'loading_gps': 'Getting location...',
      'connecting_to_nabhkrishi': 'Connecting to NabhKrishi...',
      'fetching_weather_satellite': 'Fetching weather and satellite data...',
      'loading_weather': 'Fetching weather...',
      'loading_satellite': 'Fetching satellite data...',
      'loading_analysis': 'Analyzing field conditions...',
      'loading_recommendation': 'Generating irrigation recommendation...',
      'loading_cold_start': 'Starting NabhKrishi services...',
      'error_title': 'Something went wrong',
      'error_gps_denied': 'Location permission denied. Please allow GPS access.',
      'error_gps_unavailable': 'Location services are disabled on your device.',
      'error_502': 'Satellite data is temporarily unavailable. Please try again in a moment.',
      'error_generic': 'Connection error. Please try again.',
      'retry_button': 'Retry',
      'prediction_coordinate': 'Prediction Coordinate',
      'farm_boundary': 'Farm Boundary',
      'centroid_hint': 'Predictions are calculated at the center (centroid) of your selected area.',
      'insufficient_points': 'Please tap at least 3 points on the map to define your farm area.',
      'start_drawing': 'Draw Farm Boundary',
      'undo_point': 'Undo Last Point',
      'confirm_farm_area': 'Confirm Farm Area',
      'farm_area': 'Farm Area',
      'hectares': 'hectares',
      'save_farm': 'Save Farm',
      'phone_sign_in_title': 'Enter Mobile Number',
      'phone_sign_in_subtitle': 'We will send a 6-digit OTP code to verify your phone.',
      'or_continue_with': 'Or continue with',
      'continue_phone': 'Continue with Phone',
      'continue_google': 'Continue with Google',
      'enter_phone': 'Enter Mobile Number',
      'enter_otp': 'Enter 6-digit OTP',
      'resend_otp': 'Resend OTP',
      'resend_in': 'Resend in',
      'verify_otp': 'Verify & Proceed',
      'error_invalid_phone': 'Please enter a valid 10-digit mobile number.',
      'error_invalid_otp': 'Please enter the 6-digit OTP.',
      'error_google_sign_in': 'Google Sign-In failed or cancelled.',
      'error_otp_failed': 'OTP Verification failed. Please check the code.',
      'logout_button': 'Sign Out',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'email_label': 'Email Address',
      'password_label': 'Password',
      'confirm_password_label': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'name_label': 'Full Name',
      'error_invalid_email': 'Please enter a valid email address.',
      'error_weak_password': 'Password must be at least 6 characters.',
      'error_passwords_mismatch': 'Passwords do not match.',
      'error_user_not_found': 'No account found with this email.',
      'error_wrong_password': 'Incorrect password. Please try again.',
      'error_email_in_use': 'This email is already registered.',
      'nav_home': 'Home',
      'nav_insights': 'Insights',
      'nav_scan': 'Scan',
      'nav_farm': 'Farm',
      'nav_chat': 'Ask Nabh',
      'farmer_profile': 'Farmer Profile',
      'account_settings': 'Account details and preferences',
      'active_farm_location': 'Active Farm Location',
      'coordinates': 'Coordinates',
      'farm_area_label': 'Farm Area',
      'language_preference': 'Language Preference',
      'verified_farmer': 'Verified Farmer',
      'my_wheat_field': 'My Wheat Field',
      'my_farm': 'My Farm',
      'field_health': 'Field Health',
      'satellite_view': 'Satellite View',
      'satellite_field_scan': 'Satellite Field Scan',
      'scan_wheat': 'Scan Wheat',
      'ask_nabh': 'Ask Nabh',
      'recenter': 'Recenter',
      'field_status': 'Field Status',
      'crop_stage': 'Crop Stage',
      'latest_scan': 'Latest Scan',
      'recommended_action': 'Recommended Action',
      'scanning': 'Scanning...',
      'demo_field': 'Demo Field',
      'prototype_satellite_view': 'Prototype Satellite View',
      'no_recent_scan': 'No recent AI scan',
      'no_recent_recommendation': 'No recent AI recommendation',
      'confidence_label': 'Confidence',
      'confidence_disclaimer': 'Confidence indicates AI model probability, not disease severity.',
      'view_insights': 'View Insights',
      'field_selector': 'Field Selector',
      'wheat_crop': 'Wheat (Triticum aestivum)',
      'tillering_stage': 'Crown Root / Tillering',
      'sentinel_sar_band': 'SENTINEL-1 SAR 5.4GHz',
      'vv_polarization': 'VV POLARIZATION',
      'tap_sector_hint': 'Field Sectors: R1-R4 (Tap to select)',
      'radar_signals': 'Radar Signals',
      'biomass_shift': 'Biomass Shift',
      'sentinel_age': 'Sentinel Age',
      'demo_sar_disclaimer': 'Prototype Satellite View (Demo SAR Data) • Not real-time orbital telemetry',
      'mark_your_farm': 'Mark Your Farm',
      'draw_farm_boundary_subtitle': 'Draw your farm boundary on the map',
      'draw_farm_boundary': 'Draw Farm Boundary',
      'my_location': 'My Location',
      'trace_around_boundary': 'Trace around your farm boundary',
      'clear': 'Clear',
      'done': 'Done',
      'confirm_farm_boundary': 'Confirm Farm Boundary',
      'redraw': 'Redraw',
      'redraw_boundary': 'Redraw Boundary',
      'confirm': 'Confirm',
      'farm_boundary_saved': 'Farm Boundary Saved',
      'acres': 'Acres',
      'please_trace_boundary': 'Please trace around your farm boundary.',
      'location_unavailable': 'Location unavailable. Please check device GPS.',
      'location_permission_denied': 'Location permission denied.',
      'getting_your_location': 'Getting your location...',
      'quick_actions': 'Quick Actions',
      'scan_leaf': 'Scan Leaf',
      'ask_nabh_chat': 'Ask Nabh',
      'field_map_action': 'Field Map',
      'current_status': 'Current Status',
      'wheat_optimal': 'Wheat (Optimal)',
      'satellite_radar_safe': 'Satellite radar & water index in safe zone.',
      'scan_foliage_link': 'Scan foliage →',
      'water_demand': 'Water Demand',
      'low_stress_short': 'Low stress',
      'rainfall_7d_short': '7d Rainfall',
      'adequate': 'Adequate',
      'sar_backscatter': 'SAR Backscatter',
      'avg_temp': 'Avg Temp',
      'normal': 'Normal',
      'recent_foliage_diagnosis': 'Recent Foliage Diagnosis',
      'ai_management_decision': 'AI Management Decision',
      'decision_context_footnote': 'Based on detected disease, confidence, crop stage, and field context.',
      'get_guidance': 'Get Verified Guidance',
      'recheck_photo': 'Capture Clearer Photo',
      'detected_class': 'Detected Class',
      'image_analyzed': 'Image Analyzed',
      'close': 'Close',
      'cancel': 'Cancel',
      'submit': 'Submit',
      'feedback_help': 'Help us improve NabhKrishi',
      'feedback_sub': 'How useful are our irrigation & crop recommendations?',
      'give_feedback': 'Give Feedback',
      'feedback_submitted': 'Feedback submitted!',
      'farmer_feedback': 'Farmer Feedback',
      'select_rating': 'Select Rating:',
      'comments_optional': 'Comments (optional):',
      'feedback_hint': 'Write comments here...',
      'weather_modal_title': 'Micro-Climate & Weather',
      'weather_modal_subtitle': 'Field Grid Telemetry',
      'wind_speed': 'Wind Speed',
      'rain_chance': 'Rain Chance',
      'met_advice_title': 'Meteorological Farm Advice',
      'met_advice_body': 'Low precipitation expected in next 48 hours. Safe window for foliar sprays or scheduled irrigation.',
      'agronomic_advisory_title': 'Comprehensive Advisory',
      'agronomic_advisory_subtitle': 'ICAR & University Extension',
      'field_inspection': 'Field Inspection & Monitoring',
      'field_inspection_desc': 'Regular visual inspection of leaf undersides and flag leaves for early rust or pest spotting.',
      'irrigation_mgmt': 'Irrigation Management',
      'irrigation_mgmt_desc': 'Maintain optimal soil moisture during critical crown root and tillering stages to prevent root stress.',
      'bio_mgmt': 'Preventive Bio-Management',
      'bio_mgmt_desc': 'Apply recommended Trichoderma bio-formulations or bio-fungicides during cool morning hours.',
      'kvk_helpline': 'KVK Extension Helpline',
      'kvk_helpline_sub': 'Toll-free Agronomist Support: 1800-180-1551',
      'understood': 'Understood',
      'days_together': '{days} days together 🌱',
      'icar_advisory': 'ICAR Advisory',
      'summary_heading': 'Field & Crop Health Summary',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'farmer': 'Farmer',
      'verified_farmer_account': 'Verified Farmer Account',
      'sign_out_confirm_title': 'Sign Out?',
      'sign_out_confirm_msg': 'Are you sure you want to sign out from your account?',
      'ai_server_lan': 'AI Server Connectivity (LAN)',
      'online': 'Online',
      'offline': 'Offline',
      'latitude_label': 'Latitude',
      'longitude_label': 'Longitude',
      'invalid_lat': 'Invalid Latitude (-90 to 90)',
      'invalid_lng': 'Invalid Longitude (-180 to 180)',
      'locate_farm_coords': 'Locate Farm Coordinates',
      'point_location': 'Point location',
      'active_farm_details': 'Active Farm Details',
      'no_saved_farms': 'No Saved Farms Found',
      'save_farm_first': 'Save a farm on the home screen first to track your irrigation & risk trends.',
      'insights_trends': 'Insights & Field Analytics',
      'days_filter_7': '7 Days',
      'days_filter_30': '30 Days',
      'days_filter_all': 'All Time',
      'swint_vision_result': 'Swin-T Vision Result',
      'swint_neural_analysis': 'Swin-T neural vision analysis',
      'wheat_disease_diagnosis': 'Wheat Disease Diagnosis',
      'diagnosis': 'Diagnosis',
      'ppo_decision': 'PPO Decision',
      'standard_management': 'Standard Management',
      'kvk_consultation': 'Direct consultation with plant pathologists at Krishi Vigyan Kendra.',
      'get_verified_guidance': 'Get Verified Guidance',
    },
    'hi': {
      'field_crop_summary': 'खेत एवं फसल स्वास्थ्य सारांश',
      'satellite_weather_favorable': 'उपग्रह व मौसम सूचकांक अनुकूल हैं।',
      'radar_backscatter': 'रडार बैकस्कैटर',
      'confidence_short': 'सटीकता',
      'field_map': 'खेत नक्शा',
      'farm_map_instruction': 'मानचित्र पर टैप करके सीमा बनाएं या खेत खोजें',
      'processing_radar_weather': 'मौसम व रडार टेलीमेट्री का विश्लेषण हो रहा है...',
      'irrigation_decision_footnote': 'मौसम एवं सेंटिनल-1 उपग्रह आंकड़ों के आधार पर सुरक्षित निर्णय।',
      'feedback_title': 'नभकृषि को बेहतर बनाने में मदद करें',
      'feedback_subtitle': 'हमारी सिफारिशें आपके लिए कितनी उपयोगी हैं? अपनी राय दें।',
      'farmer_feedback_form': 'किसान प्रतिक्रिया फॉर्म',
      'comments_hint': 'अपना अनुभव, सुझाव या आवश्यकताएं साझा करें...',
      'submitting': 'भेजा जा रहा है...',
      'feedback_thanks': 'धन्यवाद! आपकी प्रतिक्रिया नभकृषि को किसानों के लिए और बेहतर बनाएगी।',
      'welcome_title': 'नाभकृषि में आपका स्वागत है',
      'reset_password': 'पासवर्ड रीसेट करें',
      'welcome_subtitle': 'आपकी खेती, हमारे साथ और स्मार्ट।',
      'join_subtitle': 'नाभकृषि परिवार का हिस्सा बनने के लिए फॉर्म भरें।',
      'reset_subtitle': 'अपने पंजीकृत ईमेल पर रीसेट लिंक भेजने के लिए ईमेल दर्ज करें।',
      'trace_boundary_instruction': 'अपने खेत की सीमा के चारों ओर रेखा खींचें',
      'confirm_farm': 'खेत की पुष्टि करें',
      'boundary_confirmed': 'खेत की सीमा पुष्ट हो गई',
      'edit': 'संशोधित करें',
      'latitude': 'अक्षांश (Lat)',
      'longitude': 'देशांतर (Lng)',
      'locate_farm': 'स्थान खोजें',
      'insights_analytics': 'फसल अंतर्दृष्टि एवं रुझान',
      'insights_subtitle': 'सिंचाई सिफारिशें व वर्षा इतिहास',
      'filter_7d': '7 दिन',
      'filter_30d': '30 दिन',
      'filter_all': 'सभी',
      'field_label': 'खेत',
      'use_my_location': 'मेरी लोकेशन इस्तेमाल करें',
      'select_farm_area': 'खेत का चयन करें',
      'draw_instruction': 'अपने खेत की सीमा बनाने के लिए मानचित्र पर टैप करें।',
      'clear_boundary': 'क्षेत्र साफ़ करें',
      'confirm_location': 'खेत क्षेत्र की पुष्टि करें',
      'confirm_farm_location': 'खेत का स्थान पुष्टि करें',
      'weather_section': 'मौसम की स्थिति',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'rainfall_7d': 'वर्षा (पिछले 7 दिन)',
      'rainfall_14d': 'वर्षा (पिछले 14 दिन)',
      'et0_7d': 'ET0 (पानी की आवश्यकता)',
      'deficit_7d': 'पानी की कमी',
      'field_condition': 'मिट्टी / खेत की स्थिति',
      'estimated_water_condition': 'अनुमानित खेत की जल स्थिति',
      'low_stress': 'कम अनुमानित जल तनाव',
      'moderate_requirement': 'सामान्य पानी की आवश्यकता',
      'high_deficit': 'उच्च अनुमानित जल कमी',
      'satellite_section': 'सेंटिनल-1 सैटेलाइट जानकारी',
      'vv_mean': 'VV मीन (बैकस्कैटर)',
      'vv_change': 'VV बदलाव',
      'observation_age': 'नवीनतम अवलोकन काल',
      'satellite_freshness': 'सैटेलाइट डेटा {days} दिन पहले अपडेट हुआ था।',
      'more_details': 'अधिक जानकारी',
      'irrigation_recommendation': 'सिंचाई की सिफारिश',
      'apply_irrigation': '{amount} मिमी सिंचाई करें',
      'no_irrigation': 'सिंचाई की आवश्यकता नहीं है',
      'explanation_title': 'यह सिफारिश क्यों?',
      'loading_gps': 'लोकेशन प्राप्त की जा रही है...',
      'connecting_to_nabhkrishi': 'नभकृषि से जुड़ रहा है...',
      'fetching_weather_satellite': 'मौसम और सैटेलाइट डेटा प्राप्त किया जा रहा है...',
      'loading_weather': 'मौसम की जानकारी ली जा रही है...',
      'loading_satellite': 'सैटेलाइट डेटा प्राप्त किया जा रहा है...',
      'loading_analysis': 'खेत की स्थिति का विश्लेषण किया जा रहा है...',
      'loading_recommendation': 'सिंचाई की सिफारिश तैयार की जा रही है...',
      'loading_cold_start': 'नभकृषि सेवाएं शुरू हो रही हैं...',
      'error_title': 'कुछ गड़बड़ हो गई',
      'error_gps_denied': 'लोकेशन की अनुमति अस्वीकृत। कृपया जीपीएस एक्सेस प्रदान करें।',
      'error_gps_unavailable': 'आपके डिवाइस पर लोकेशन सेवाएं बंद हैं।',
      'error_502': 'सैटेलाइट डेटा अस्थायी रूप से अनुपलब्ध है। कृपया कुछ ही क्षणों में पुनः प्रयास करें।',
      'error_generic': 'कनेक्शन त्रुटि। कृपया पुनः प्रयास करें।',
      'retry_button': 'पुनः प्रयास करें',
      'prediction_coordinate': 'अनुमानित निर्देशांक',
      'farm_boundary': 'खेत की सीमा',
      'centroid_hint': 'अनुमान आपके चयनित क्षेत्र के केंद्र (सेंट्रॉइड) पर आधारित हैं।',
      'insufficient_points': 'कृपया अपने खेत के क्षेत्र को परिभाषित करने के लिए मानचित्र पर कम से कम 3 बिंदुओं को टैप करें।',
      'start_drawing': 'खेत की सीमा बनाएं',
      'undo_point': 'पूर्ववत करें',
      'confirm_farm_area': 'खेत की पुष्टि करें',
      'farm_area': 'खेत का क्षेत्रफल',
      'hectares': 'हेक्टेयर',
      'save_farm': 'खेत सहेजें',
      'phone_sign_in_title': 'मोबाइल नंबर दर्ज करें',
      'phone_sign_in_subtitle': 'आपके फोन को सत्यापित करने के लिए हम 6 अंकों का OTP भेजेंगे।',
      'or_continue_with': 'या इसके साथ आगे बढ़ें',
      'continue_phone': 'फोन के साथ आगे बढ़ें',
      'continue_google': 'गूगल के साथ आगे बढ़ें',
      'enter_phone': 'मोबाइल नंबर दर्ज करें',
      'enter_otp': '6 अंकों का OTP दर्ज करें',
      'resend_otp': 'OTP पुनः भेजें',
      'resend_in': 'पुनः भेजें',
      'verify_otp': 'सत्यापित करें और आगे बढ़ें',
      'error_invalid_phone': 'कृपया 10 अंकों का मोबाइल नंबर दर्ज करें।',
      'error_invalid_otp': 'कृपया 6 अंकों का OTP दर्ज करें।',
      'error_google_sign_in': 'गूगल लॉगिन विफल या रद्द कर दिया गया।',
      'error_otp_failed': 'OTP सत्यापन विफल। कृपया कोड जांचें।',
      'logout_button': 'लॉग आउट',
      'sign_in': 'साइन इन करें',
      'create_account': 'खाता बनाएं',
      'email_label': 'ईमेल पता',
      'password_label': 'पासवर्ड',
      'confirm_password_label': 'पासवर्ड की पुष्टि करें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have_account': 'खाता नहीं है?',
      'already_have_account': 'पहले से खाता है?',
      'name_label': 'पूरा नाम',
      'error_invalid_email': 'कृपया एक मान्य ईमेल पता दर्ज करें।',
      'error_weak_password': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'error_passwords_mismatch': 'पासवर्ड मेल नहीं खाते हैं।',
      'error_user_not_found': 'इस ईमेल से कोई खाता नहीं मिला।',
      'error_wrong_password': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
      'error_email_in_use': 'यह ईमेल पहले से ही पंजीकृत है।',
      'nav_home': 'होम',
      'nav_insights': 'अंतर्दृष्टि',
      'nav_scan': 'स्कैन',
      'nav_farm': 'खेत',
      'nav_chat': 'नभ AI',
      'farmer_profile': 'किसान प्रोफ़ाइल',
      'account_settings': 'खाता विवरण व सेटिंग्स',
      'active_farm_location': 'सक्रिय खेत स्थान',
      'coordinates': 'अक्षांश / देशांतर',
      'farm_area_label': 'खेत क्षेत्र',
      'language_preference': 'भाषा प्राथमिकता',
      'verified_farmer': 'सत्यापित किसान',
      'my_wheat_field': 'मेरा गेहूं का खेत',
      'my_farm': 'मेरा खेत',
      'field_health': 'खेत का स्वास्थ्य',
      'satellite_view': 'उपग्रह दृश्य',
      'satellite_field_scan': 'उपग्रह खेत स्कैन',
      'scan_wheat': 'गेहूं स्कैन करें',
      'ask_nabh': 'नभ से पूछें',
      'recenter': 'पुनः केंद्रित करें',
      'field_status': 'खेत की स्थिति',
      'crop_stage': 'फसल अवस्था',
      'latest_scan': 'नवीनतम स्कैन',
      'recommended_action': 'अनुशंसित कार्रवाई',
      'scanning': 'स्कैनिंग जारी है...',
      'demo_field': 'डेमो खेत',
      'prototype_satellite_view': 'प्रोटोटाइप उपग्रह दृश्य',
      'no_recent_scan': 'हाल ही में कोई एआई स्कैन नहीं',
      'no_recent_recommendation': 'हाल ही में कोई एआई सिफारिश नहीं',
      'confidence_label': 'सटीकता (Confidence)',
      'confidence_disclaimer': 'सटीकता एआई मॉडल की पहचान संभावना है, रोग की गंभीरता नहीं।',
      'view_insights': 'विश्लेषण देखें',
      'field_selector': 'खेत चयन',
      'wheat_crop': 'गेहूं (ट्रिटिकम एस्टिवम)',
      'tillering_stage': 'कल्ले फूटना (Tillering)',
      'sentinel_sar_band': 'सेंटिनल-1 सार रडार 5.4GHz',
      'vv_polarization': 'VV ध्रुवीकरण',
      'tap_sector_hint': 'खेत क्षेत्र: R1-R4 (चयन हेतु टैप करें)',
      'radar_signals': 'रडार सिग्नल्स',
      'biomass_shift': 'बायोमास परिवर्तन',
      'sentinel_age': 'सेंटिनल आयु',
      'demo_sar_disclaimer': 'प्रोटोटाइप उपग्रह दृश्य (डेमो सार डेटा) • वास्तविक कक्षा टेलीमेट्री नहीं',
      'mark_your_farm': 'अपने खेत को चिह्नित करें',
      'draw_farm_boundary_subtitle': 'मानचित्र पर अपने खेत की सीमा बनाएं',
      'draw_farm_boundary': 'खेत की सीमा बनाएं',
      'my_location': 'मेरी लोकेशन',
      'trace_around_boundary': 'अपने खेत की सीमा के चारों ओर उंगली से रेखा खींचें',
      'clear': 'साफ़ करें',
      'done': 'संपन्न',
      'confirm_farm_boundary': 'खेत की सीमा की पुष्टि करें',
      'redraw': 'पुनः बनाएं',
      'redraw_boundary': 'सीमा पुनः बनाएं',
      'confirm': 'पुष्टि करें',
      'farm_boundary_saved': 'खेत की सीमा सहेजी गई',
      'acres': 'एकड़',
      'please_trace_boundary': 'कृपया अपने खेत की सीमा के चारों ओर रेखा खींचें।',
      'location_unavailable': 'लोकेशन अनुपलब्ध है। कृपया जीपीएस जांचें।',
      'location_permission_denied': 'लोकेशन की अनुमति अस्वीकृत।',
      'getting_your_location': 'आपकी लोकेशन प्राप्त की जा रही है...',
      'quick_actions': 'त्वरित कार्य',
      'scan_leaf': 'पत्ती स्कैन',
      'ask_nabh_chat': 'नभ चैट',
      'field_map_action': 'खेत नक्शा',
      'current_status': 'वर्तमान फसल स्थिति',
      'wheat_optimal': 'गेहूं (स्थिर विकास)',
      'satellite_radar_safe': 'उपग्रह व मौसम सूचकांक अनुकूल हैं।',
      'scan_foliage_link': 'पत्ती स्कैन करें →',
      'water_demand': 'जल मांग',
      'low_stress_short': 'निम्न तनाव',
      'rainfall_7d_short': '7-दिन वर्षा',
      'adequate': 'पर्याप्त',
      'sar_backscatter': 'रडार बैकस्कैटर',
      'avg_temp': 'औसत तापमान',
      'normal': 'सामान्य',
      'recent_foliage_diagnosis': 'हालिया फसल निदान',
      'ai_management_decision': 'एआई निर्णय सहायता (PPO V3)',
      'decision_context_footnote': 'पहचाने गए रोग, सटीकता, फसल अवस्था और खेत संदर्भ पर आधारित निर्णय सहायता।',
      'get_guidance': 'सलाह प्राप्त करें (Ask Nabh)',
      'recheck_photo': 'पुनः स्पष्ट फोटो लें',
      'detected_class': 'पहचाना गया परिणाम',
      'image_analyzed': 'विश्लेषण संपन्न',
      'close': 'बंद करें',
      'cancel': 'रद्द करें',
      'submit': 'जमा करें',
      'feedback_help': 'नभकृषि को बेहतर बनाने में मदद करें',
      'feedback_sub': 'हमारी सिफारिशें आपके लिए कितनी उपयोगी हैं? अपनी राय दें।',
      'give_feedback': 'प्रतिक्रिया दें',
      'feedback_submitted': 'प्रतिक्रिया दर्ज हुई!',
      'farmer_feedback': 'किसान प्रतिक्रिया फॉर्म',
      'select_rating': 'रेटिंग चुनें:',
      'comments_optional': 'टिप्पणी (वैकल्पिक):',
      'feedback_hint': 'अपनी प्रतिक्रिया यहाँ लिखें...',
      'weather_modal_title': 'मौसम एवं वर्षा रडार',
      'weather_modal_subtitle': 'स्थान आधारित पूर्वानुमान',
      'wind_speed': 'हवा की गति',
      'rain_chance': 'वर्षा संभावना',
      'met_advice_title': 'कृषि मौसम सलाह',
      'met_advice_body': 'अगले 48 घंटों में भारी बारिश की संभावना कम है। पत्ती पर स्प्रे या हल्की सिंचाई की जा सकती है।',
      'agronomic_advisory_title': 'फसल सुरक्षा परामर्श',
      'agronomic_advisory_subtitle': 'कृषि विज्ञान केंद्र एवं ICAR दिशा-निर्देश',
      'field_inspection': 'निगरानी एवं पत्ती निरीक्षण',
      'field_inspection_desc': 'रतुआ या कीट के शुरुआती लक्षणों के लिए पत्तियों की नियमित निगरानी करें।',
      'irrigation_mgmt': 'सिंचाई नियंत्रण',
      'irrigation_mgmt_desc': 'कल्ले फूटते समय खेत में नमी का उचित स्तर बनाए रखें ताकि जड़ों पर तनाव न आए।',
      'bio_mgmt': 'रोकथाम एवं जैविक उपचार',
      'bio_mgmt_desc': 'सुबह के समय ट्राइकोडर्मा या अनुशंसित जैविक फफूंदनाशी का छिड़काव करें।',
      'kvk_helpline': 'स्थानीय केवीके हेल्पलाइन',
      'kvk_helpline_sub': 'कृषि वैज्ञानिकों से सीधे मार्गदर्शन हेतु: 1800-180-1551',
      'understood': 'ठीक है',
      'days_together': 'साथ में {days} दिन 🌱',
      'icar_advisory': 'ICAR सलाह',
      'summary_heading': 'खेत एवं फसल स्वास्थ्य सारांश',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'नमस्ते',
      'good_evening': 'शुभ संध्या',
      'farmer': 'किसान मित्र',
      'verified_farmer_account': 'सत्यापित किसान खाता',
      'sign_out_confirm_title': 'लॉग आउट करें?',
      'sign_out_confirm_msg': 'क्या आप वाकई अपने खाते से लॉग आउट करना चाहते हैं?',
      'ai_server_lan': 'एआई सर्वर स्थिति (LAN)',
      'online': 'ऑनलाइन',
      'offline': 'अनुपलब्ध',
      'latitude_label': 'अक्षांश (Lat)',
      'longitude_label': 'देशांतर (Lng)',
      'invalid_lat': 'अमान्य अक्षांश (-90 से 90)',
      'invalid_lng': 'अमान्य देशांतर (-180 से 180)',
      'locate_farm_coords': 'स्थान खोजें',
      'point_location': 'बिंदु स्थान (सीमा नहीं खींची गई)',
      'active_farm_details': 'सक्रिय खेत विवरण',
      'no_saved_farms': 'कोई खेत सहेजा नहीं गया',
      'save_farm_first': 'विश्लेषिकी डेटा देखने के लिए पहले होम स्क्रीन पर एक खेत चुनें और सहेजें।',
      'insights_trends': 'फसल अंतर्दृष्टि एवं रुझान',
      'days_filter_7': '7 दिन',
      'days_filter_30': '30 दिन',
      'days_filter_all': 'सम्पूर्ण',
      'swint_vision_result': 'पहचाना गया परिणाम (Swin-T)',
      'swint_neural_analysis': 'पत्ती विश्लेषण परिणाम',
      'wheat_disease_diagnosis': 'गेहूं रोग निदान (Swin-T)',
      'diagnosis': 'रोग पहचान',
      'ppo_decision': 'निर्णय',
      'standard_management': 'सामान्य प्रबंधन',
      'kvk_consultation': 'कृषि विज्ञान केंद्र (KVK) एवं ICAR पादप रोग वैज्ञानिकों से परामर्श लें।',
      'get_verified_guidance': 'सलाह प्राप्त करें (Get Guidance)',
    },
    'pa': {
      'field_crop_summary': 'ਖੇਤ ਅਤੇ ਫ਼ਸਲ ਸਿਹਤ ਸਾਰਾਂਸ਼',
      'satellite_weather_favorable': 'ਉਪਗ੍ਰਹਿ ਅਤੇ ਮੌਸਮ ਸੂਚਕਾਂਕ ਸੁਰੱਖਿਅਤ ਹਨ।',
      'radar_backscatter': 'ਰਡਾਰ ਬੈਕਸਕੈਟਰ',
      'confidence_short': 'ਸ਼ੁੱਧਤਾ',
      'field_map': 'ਖੇਤ ਨਕਸ਼ਾ',
      'farm_map_instruction': 'ਨਕਸ਼ੇ ਤੇ ਸੀਮਾ ਖਿੱਚੋ ਜਾਂ GPS ਰਾਹੀਂ ਖੇਤ ਲੱਭੋ',
      'processing_radar_weather': 'ਮੌਸਮ ਅਤੇ ਰਡਾਰ ਡਾਟਾ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...',
      'irrigation_decision_footnote': 'ਮੌਸਮ ਅਤੇ ਸੈਂਟੀਨਲ-1 ਉਪਗ੍ਰਹਿ ਅੰਕੜਿਆਂ ਤੇ ਆਧਾਰਿਤ ਫ਼ੈਸਲਾ।',
      'feedback_title': 'ਨਾਭਕ੍ਰਿਸ਼ੀ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰੋ',
      'feedback_subtitle': 'ਸਾਡੀ ਸਲਾਹ ਤੁਹਾਡੇ ਲਈ ਕਿੰਨੀ ਲਾਭਦਾਇਕ ਹੈ? ਆਪਣੀ ਰਾਏ ਦਿਓ।',
      'farmer_feedback_form': 'ਕਿਸਾਨ ਸੁਝਾਅ ਫਾਰਮ',
      'comments_hint': 'ਆਪਣਾ ਅਨੁਭਵ ਜਾਂ ਸੁਝਾਅ ਸਾਂਝਾ ਕਰੋ...',
      'submitting': 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      'feedback_thanks': 'ਧੰਨਵਾਦ! ਤੁਹਾਡਾ ਸੁਝਾਅ ਨਾਭਕ੍ਰਿਸ਼ੀ ਨੂੰ ਹੋਰ ਬਿਹਤਰ ਬਣਾਏਗਾ।',
      'welcome_title': 'ਨਾਭਕ੍ਰਿਸ਼ੀ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
      'reset_password': 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ',
      'welcome_subtitle': 'ਤੁਹਾਡੀ ਖੇਤੀ, ਸਾਡੇ ਨਾਲ ਹੋਰ ਸਮਾਰਟ।',
      'join_subtitle': 'ਨਾਭਕ੍ਰਿਸ਼ੀ ਪਰਿਵਾਰ ਨਾਲ ਜੁੜਨ ਲਈ ਫਾਰਮ ਭਰੋ।',
      'reset_subtitle': 'ਪਾਸਵਰਡ ਲਿੰਕ ਲਈ ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ।',
      'trace_boundary_instruction': 'ਆਪਣੇ ਖੇਤ ਦੀ ਸੀਮਾ ਦੇ ਦੁਆਲੇ ਲਾਈਨ ਖਿੱਚੋ',
      'confirm_farm': 'ਖੇਤ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'boundary_confirmed': 'ਖੇਤ ਦੀ ਸੀਮਾ ਪੁਸ਼ਟ ਹੋਈ',
      'edit': 'ਬਦਲੋ',
      'latitude': 'ਅਕਸ਼ਾਂਸ਼ (Lat)',
      'longitude': 'ਰੇਖਾਂਸ਼ (Lng)',
      'locate_farm': 'ਖੇਤ ਲੱਭੋ',
      'insights_analytics': 'ਫ਼ਸਲ ਜਾਣਕਾਰੀ ਅਤੇ ਰੁਝਾਨ',
      'insights_subtitle': 'ਸਿੰਚਾਈ ਸਲਾਹ ਅਤੇ ਨਮੀ ਇਤਿਹਾਸ',
      'filter_7d': '7 ਦਿਨ',
      'filter_30d': '30 ਦਿਨ',
      'filter_all': 'ਸਾਰੇ',
      'field_label': 'ਖੇਤ',
      'use_my_location': 'ਮੇਰੀ ਲੋਕੇਸ਼ਨ ਵਰਤੋ',
      'select_farm_area': 'ਖੇਤ ਦਾ ਖੇਤਰ ਚੁਣੋ',
      'draw_instruction': 'ਆਪਣੇ ਖੇਤ ਦੀ ਹੱਦ ਬਣਾਉਣ ਲਈ ਨਕਸ਼ੇ ਤੇ ਟੈਪ ਕਰੋ।',
      'clear_boundary': 'ਖੇਤਰ ਸਾਫ਼ ਕਰੋ',
      'confirm_location': 'ਖੇਤ ਖੇਤਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'confirm_farm_location': 'ਖੇਤ ਦੀ ਲੋਕੇਸ਼ਨ ਪੁਸ਼ਟੀ ਕਰੋ',
      'weather_section': 'ਮੌਸਮ ਦੀ ਸਥਿਤੀ',
      'temperature': 'ਤਾਪਮਾਨ',
      'humidity': 'ਨਮੀ',
      'rainfall_7d': 'ਮੀਂਹ (ਪਿਛਲੇ 7 ਦਿਨ)',
      'rainfall_14d': 'ਮੀਂਹ (ਪਿਛਲੇ 14 ਦਿਨ)',
      'et0_7d': 'ET0 (ਪਾਣੀ ਦੀ ਮੰਗ)',
      'deficit_7d': 'ਪਾਣੀ ਦੀ ਕਮੀ',
      'field_condition': 'ਮਿੱਟੀ / ਖੇਤ ਦੀ ਸਥਿਤੀ',
      'estimated_water_condition': 'ਅਨੁਮਾਨਿਤ ਖੇਤ ਪਾਣੀ ਦੀ ਸਥਿਤੀ',
      'low_stress': 'ਘੱਟ ਪਾਣੀ ਦਾ ਤਣਾਅ',
      'moderate_requirement': 'ਦਰਮਿਆਨੀ ਪਾਣੀ ਦੀ ਲੋੜ',
      'high_deficit': 'ਵੱਧ ਪਾਣੀ ਦੀ ਕਮੀ',
      'satellite_section': 'ਸੈਂਟੀਨਲ-1 ਸੈਟੇਲਾਈਟ ਜਾਣਕਾਰੀ',
      'vv_mean': 'VV ਮੀਨ',
      'vv_change': 'VV ਬਦਲਾਅ',
      'observation_age': 'ਤਾਜ਼ਾ ਨਿਰੀਖਣ ਸਮਾਂ',
      'satellite_freshness': 'ਸੈਟੇਲਾਈਟ ਡਾਟਾ {days} ਦਿਨ ਪਹਿਲਾਂ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ ਸੀ।',
      'more_details': 'ਹੋਰ ਵੇਰਵੇ',
      'irrigation_recommendation': 'ਸਿੰਚਾਈ ਦੀ ਸਿਫ਼ਾਰਸ਼',
      'apply_irrigation': '{amount} ਮਿਲੀਮੀਟਰ ਸਿੰਚਾਈ ਕਰੋ',
      'no_irrigation': 'ਸਿੰਚਾਈ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ',
      'explanation_title': 'ਇਹ ਸਿਫ਼ਾਰਸ਼ ਕਿਉਂ?',
      'loading_gps': 'ਲੋਕੇਸ਼ਨ ਲਈ ਜਾ ਰਹੀ ਹੈ...',
      'connecting_to_nabhkrishi': 'ਨਾਭਕ੍ਰਿਸ਼ੀ ਨਾਲ ਜੁੜ ਰਿਹਾ ਹੈ...',
      'fetching_weather_satellite': 'ਮੌਸਮ ਅਤੇ ਸੈਟੇਲਾਈਟ ਡਾਟਾ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      'loading_weather': 'ਮੌਸਮ ਦੀ ਜਾਣਕਾਰੀ ਲਈ ਜਾ ਰਹੀ ਹੈ...',
      'loading_satellite': 'ਸੈਟੇਲਾਈਟ ਡਾਟਾ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
      'loading_analysis': 'ਖੇਤ ਦੀ ਸਥਿਤੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
      'loading_recommendation': 'ਸਿੰਚਾਈ ਸਿਫ਼ਾਰਸ਼ ਤਿਆਰ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
      'loading_cold_start': 'ਨਾਭਕ੍ਰਿਸ਼ੀ ਸੇਵਾਵਾਂ ਸ਼ੁਰੂ ਹੋ ਰਹੀਆਂ ਹਨ...',
      'error_title': 'ਕੁਝ ਗੜਬੜ ਹੋ ਗਈ',
      'error_gps_denied': 'ਲੋਕੇਸ਼ਨ ਆਗਿਆ ਰੱਦ ਕੀਤੀ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ GPS ਚਾਲੂ ਕਰੋ।',
      'error_gps_unavailable': 'ਤੁਹਾਡੇ ਫ਼ੋਨ ਤੇ ਲੋਕੇਸ਼ਨ ਸੇਵਾਵਾਂ ਬੰਦ ਹਨ।',
      'error_502': 'ਸੈਟੇਲਾਈਟ ਡਾਟਾ ਅਸਥਾਈ ਤੌਰ ਤੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
      'error_generic': 'ਕਨੈਕਸ਼ਨ ਗੜਬੜ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'retry_button': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'prediction_coordinate': 'ਅਨੁਮਾਨਿਤ ਨਿਰਦੇਸ਼ਾਂਕ',
      'farm_boundary': 'ਖੇਤ ਦੀ ਹੱਦ',
      'centroid_hint': 'ਅਨੁਮਾਨ ਤੁਹਾਡੇ ਚੁਣੇ ਹੋਏ ਖੇਤਰ ਦੇ ਕੇਂਦਰ ਤੇ ਅਧਾਰਤ ਹਨ।',
      'insufficient_points': 'ਆਪਣੇ ਖੇਤ ਖੇਤਰ ਲਈ ਨਕਸ਼ੇ ਤੇ ਘੱਟੋ-ਘੱਟ 3 ਬਿੰਦੂ ਚੁਣੋ।',
      'start_drawing': 'ਖੇਤ ਦੀ ਹੱਦ ਬਣਾਓ',
      'undo_point': 'ਪਿਛਲਾ ਬਿੰਦੂ ਹਟਾਓ',
      'confirm_farm_area': 'ਖੇਤ ਖੇਤਰ ਪੱਕਾ ਕਰੋ',
      'farm_area': 'ਖੇਤ ਦਾ ਰਕਬਾ',
      'hectares': 'ਹੈਕਟੇਅਰ',
      'save_farm': 'ਖੇਤ ਸੇਵ ਕਰੋ',
      'phone_sign_in_title': 'ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'phone_sign_in_subtitle': 'ਅਸੀਂ ਤੁਹਾਡੇ ਫ਼ੋਨ ਦੀ ਪੁਸ਼ਟੀ ਲਈ 6 ਅੰਕਾਂ ਦਾ OTP ਭੇਜਾਂਗੇ।',
      'or_continue_with': 'ਜਾਂ ਇਸ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      'continue_phone': 'ਫ਼ੋਨ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      'continue_google': 'ਗੂਗਲ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
      'enter_phone': 'ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'enter_otp': '6 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ',
      'resend_otp': 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
      'resend_in': 'ਦੁਬਾਰਾ ਭੇਜੋ',
      'verify_otp': 'ਤਸਦੀਕ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ',
      'error_invalid_phone': 'ਕਿਰਪਾ ਕਰਕੇ 10 ਅੰਕਾਂ ਦਾ ਸਹੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
      'error_invalid_otp': 'ਕਿਰਪਾ ਕਰਕੇ 6 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ।',
      'error_google_sign_in': 'ਗੂਗਲ ਲੌਗਇਨ ਅਸਫ਼ਲ ਰਿਹਾ।',
      'error_otp_failed': 'OTP ਤਸਦੀਕ ਅਸਫ਼ਲ ਰਹੀ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਡ ਜਾਂਚੋ।',
      'logout_button': 'ਸਾਈਨ ਆਊਟ',
      'sign_in': 'ਸਾਈਨ ਇਨ',
      'create_account': 'ਖਾਤਾ ਬਣਾਓ',
      'email_label': 'ਈਮੇਲ ਪਤਾ',
      'password_label': 'ਪਾਸਵਰਡ',
      'confirm_password_label': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'forgot_password': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
      'dont_have_account': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
      'already_have_account': 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
      'name_label': 'ਪੂਰਾ ਨਾਮ',
      'error_invalid_email': 'ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
      'error_weak_password': 'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
      'error_passwords_mismatch': 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ।',
      'error_user_not_found': 'ਇਸ ਈਮੇਲ ਨਾਲ ਕੋਈ ਖਾਤਾ ਨਹੀਂ ਮਿਲਿਆ।',
      'error_wrong_password': 'ਗ਼ਲਤ ਪਾਸਵਰਡ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
      'error_email_in_use': 'ਇਹ ਈਮੇਲ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ।',
      'nav_home': 'ਮੁੱਖ',
      'nav_insights': 'ਜਾਣਕਾਰੀ',
      'nav_scan': 'ਸਕੈਨ',
      'nav_farm': 'ਖੇਤ',
      'nav_chat': 'ਨਭ AI',
      'farmer_profile': 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
      'account_settings': 'ਖਾਤਾ ਵੇਰਵਾ ਅਤੇ ਸੈਟਿੰਗਾਂ',
      'active_farm_location': 'ਸਰਗਰਮ ਖੇਤ ਲੋਕੇਸ਼ਨ',
      'coordinates': 'ਨਿਰਦੇਸ਼ਾਂਕ',
      'farm_area_label': 'ਖੇਤ ਦਾ ਰਕਬਾ',
      'language_preference': 'ਭਾਸ਼ਾ ਤਰਜੀਹ',
      'verified_farmer': 'ਪ੍ਰਮਾਣਿਤ ਕਿਸਾਨ',
      'my_wheat_field': 'ਮੇਰਾ ਕਣਕ ਦਾ ਖੇਤ',
      'my_farm': 'ਮੇਰਾ ਖੇਤ',
      'field_health': 'ਖੇਤ ਦੀ ਸਿਹਤ',
      'satellite_view': 'ਸੈਟੇਲਾਈਟ ਦ੍ਰਿਸ਼',
      'satellite_field_scan': 'ਸੈਟੇਲਾਈਟ ਖੇਤ ਸਕੈਨ',
      'scan_wheat': 'ਕਣਕ ਸਕੈਨ ਕਰੋ',
      'ask_nabh': 'ਨਾਭ ਤੋਂ ਪੁੱਛੋ',
      'recenter': 'ਮੁੜ ਕੇਂਦਰਿਤ ਕਰੋ',
      'field_status': 'ਖੇਤ ਦੀ ਸਥਿਤੀ',
      'crop_stage': 'ਫ਼ਸਲ ਦਾ ਪੜਾਅ',
      'latest_scan': 'ਤਾਜ਼ਾ ਸਕੈਨ',
      'recommended_action': 'ਸਿਫ਼ਾਰਸ਼ੀ ਕਾਰਵਾਈ',
      'scanning': 'ਸਕੈਨਿੰਗ ਜਾਰੀ ਹੈ...',
      'demo_field': 'ਡੈਮੋ ਖੇਤ',
      'prototype_satellite_view': 'ਪ੍ਰੋਟੋਟਾਈਪ ਸੈਟੇਲਾਈਟ ਦ੍ਰਿਸ਼',
      'no_recent_scan': 'ਕੋਈ ਤਾਜ਼ਾ AI ਸਕੈਨ ਨਹੀਂ',
      'no_recent_recommendation': 'ਕੋਈ ਤਾਜ਼ਾ AI ਸਿਫ਼ਾਰਸ਼ ਨਹੀਂ',
      'confidence_label': 'ਭਰੋਸੇਯੋਗਤਾ (Confidence)',
      'confidence_disclaimer': 'ਭਰੋਸੇਯੋਗਤਾ AI ਮਾਡਲ ਦੀ ਪਛਾਣ ਸੰਭਾਵਨਾ ਹੈ, ਰੋਗ ਦੀ ਗੰਭੀਰਤਾ ਨਹੀਂ।',
      'view_insights': 'ਜਾਣਕਾਰੀ ਦੇਖੋ',
      'field_selector': 'ਖੇਤ ਚੋਣ',
      'wheat_crop': 'ਕਣਕ (ਟ੍ਰਿਟਿਕਮ ਐਸਟੀਵਮ)',
      'tillering_stage': 'ਸ਼ਾਖਾਵਾਂ ਫੁੱਟਣਾ (Tillering)',
      'sentinel_sar_band': 'ਸੈਂਟੀਨਲ-1 SAR ਰਡਾਰ 5.4GHz',
      'vv_polarization': 'VV ਪੋਲਰਾਈਜ਼ੇਸ਼ਨ',
      'tap_sector_hint': 'ਖੇਤ ਖੇਤਰ: R1-R4 (ਚੁਣਨ ਲਈ ਟੈਪ ਕਰੋ)',
      'radar_signals': 'ਰਡਾਰ ਸਿਗਨਲ',
      'biomass_shift': 'ਬਾਇਓਮਾਸ ਬਦਲਾਅ',
      'sentinel_age': 'ਸੈਂਟੀਨਲ ਸਮਾਂ',
      'demo_sar_disclaimer': 'ਪ੍ਰੋਟੋਟਾਈਪ ਸੈਟੇਲਾਈਟ ਦ੍ਰਿਸ਼ (ਡੈਮੋ SAR ਡਾਟਾ) • ਅਸਲ ਆਰਬਿਟਲ ਟੈਲੀਮੈਟਰੀ ਨਹੀਂ',
      'mark_your_farm': 'ਆਪਣੇ ਖੇਤ ਦੀ ਨਿਸ਼ਾਨਦੇਹੀ ਕਰੋ',
      'draw_farm_boundary_subtitle': 'ਨਕਸ਼ੇ ਉੱਤੇ ਆਪਣੇ ਖੇਤ ਦੀ ਹੱਦ ਬਣਾਓ',
      'draw_farm_boundary': 'ਖੇਤ ਦੀ ਹੱਦ ਬਣਾਓ',
      'my_location': 'ਮੇਰੀ ਲੋਕੇਸ਼ਨ',
      'trace_around_boundary': 'ਆਪਣੇ ਖੇਤ ਦੀ ਹੱਦ ਦੁਆਲੇ ਉਂਗਲੀ ਨਾਲ ਲਕੀਰ ਖਿੱਚੋ',
      'clear': 'ਸਾਫ਼ ਕਰੋ',
      'done': 'ਸੰਪੰਨ',
      'confirm_farm_boundary': 'ਖੇਤ ਦੀ ਹੱਦ ਪੱਕੀ ਕਰੋ',
      'redraw': 'ਦੁਬਾਰਾ ਬਣਾਓ',
      'redraw_boundary': 'ਹੱਦ ਦੁਬਾਰਾ ਬਣਾਓ',
      'confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
      'farm_boundary_saved': 'ਖੇਤ ਦੀ ਹੱਦ ਸੁਰੱਖਿਅਤ ਕੀਤੀ ਗਈ',
      'acres': 'ਏਕੜ',
      'please_trace_boundary': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਖੇਤ ਦੀ ਹੱਦ ਦੁਆਲੇ ਲਕੀਰ ਖਿੱਚੋ।',
      'location_unavailable': 'ਲੋਕੇਸ਼ਨ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। GPS ਚੈੱਕ ਕਰੋ।',
      'location_permission_denied': 'ਲੋਕੇਸ਼ਨ ਆਗਿਆ ਰੱਦ ਕੀਤੀ ਗਈ।',
      'getting_your_location': 'ਤੁਹਾਡੀ ਲੋਕੇਸ਼ਨ ਪ੍ਰਾਪਤ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
      'quick_actions': 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
      'scan_leaf': 'ਪੱਤਾ ਸਕੈਨ',
      'ask_nabh_chat': 'ਨਾਭ ਚੈਟ',
      'field_map_action': 'ਖੇਤ ਨਕਸ਼ਾ',
      'current_status': 'ਮੌਜੂਦਾ ਫ਼ਸਲ ਸਥਿਤੀ',
      'wheat_optimal': 'ਕਣਕ (ਵਧੀਆ ਵਿਕਾਸ)',
      'satellite_radar_safe': 'ਸੈਟੇਲਾਈਟ ਰਡਾਰ ਅਤੇ ਪਾਣੀ ਸੂਚਕ ਅਨੁਕੂਲ ਹਨ।',
      'scan_foliage_link': 'ਪੱਤਾ ਸਕੈਨ ਕਰੋ →',
      'water_demand': 'ਪਾਣੀ ਦੀ ਮੰਗ',
      'low_stress_short': 'ਘੱਟ ਤਣਾਅ',
      'rainfall_7d_short': '7-ਦਿਨ ਮੀਂਹ',
      'adequate': 'ਲੋੜੀਂਦਾ',
      'sar_backscatter': 'ਰਡਾਰ ਬੈਕਸਕੈਟਰ',
      'avg_temp': 'ਔਸਤ ਤਾਪਮਾਨ',
      'normal': 'ਆਮ',
      'recent_foliage_diagnosis': 'ਤਾਜ਼ਾ ਫ਼ਸਲ ਜਾਂਚ',
      'ai_management_decision': 'AI ਪ੍ਰਬੰਧਨ ਫ਼ੈਸਲਾ',
      'decision_context_footnote': 'ਪਛਾਣੇ ਗਏ ਰੋਗ, ਭਰੋਸੇਯੋਗਤਾ, ਫ਼ਸਲ ਪੜਾਅ ਅਤੇ ਖੇਤ ਸੰਦਰਭ ਤੇ ਆਧਾਰਿਤ।',
      'get_guidance': 'ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ (Ask Nabh)',
      'recheck_photo': 'ਸਾਫ਼ ਫੋਟੋ ਲਓ',
      'detected_class': 'ਪਛਾਣਿਆ ਗਿਆ ਨਤੀਜਾ',
      'image_analyzed': 'ਵਿਸ਼ਲੇਸ਼ਣ ਸੰਪੰਨ',
      'close': 'ਬੰਦ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'submit': 'ਜਮ੍ਹਾ ਕਰੋ',
      'feedback_help': 'ਨਾਭਕ੍ਰਿਸ਼ੀ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰੋ',
      'feedback_sub': 'ਸਾਡੀਆਂ ਸਿਫ਼ਾਰਸ਼ਾਂ ਤੁਹਾਡੇ ਲਈ ਕਿੰਨੀਆਂ ਲਾਭਦਾਇਕ ਹਨ?',
      'give_feedback': 'ਫੀਡਬੈਕ ਦਿਓ',
      'feedback_submitted': 'ਫੀਡਬੈਕ ਦਰਜ ਹੋ ਗਿਆ!',
      'farmer_feedback': 'ਕਿਸਾਨ ਫੀਡਬੈਕ ਫਾਰਮ',
      'select_rating': 'ਰੇਟਿੰਗ ਚੁਣੋ:',
      'comments_optional': 'ਟਿੱਪਣੀ (ਵਿਕਲਪਿਕ):',
      'feedback_hint': 'ਆਪਣੀ ਫੀਡਬੈਕ ਇੱਥੇ ਲਿਖੋ...',
      'weather_modal_title': 'ਮੌਸਮ ਅਤੇ ਮੀਂਹ ਰਡਾਰ',
      'weather_modal_subtitle': 'ਸਥਾਨ ਆਧਾਰਿਤ ਪੂਰਵ-ਅਨੁਮਾਨ',
      'wind_speed': 'ਹਵਾ ਦੀ ਰਫ਼ਤਾਰ',
      'rain_chance': 'ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ',
      'met_advice_title': 'ਖੇਤੀ ਮੌਸਮ ਸਲਾਹ',
      'met_advice_body': 'ਅਗਲੇ 48 ਘੰਟਿਆਂ ਵਿੱਚ ਭਾਰੀ ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ ਘੱਟ ਹੈ। ਪੱਤੇ ਤੇ ਸਪਰੇਅ ਜਾਂ ਸਿੰਚਾਈ ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ।',
      'agronomic_advisory_title': 'ਫ਼ਸਲ ਸੁਰੱਖਿਆ ਸਲਾਹ',
      'agronomic_advisory_subtitle': 'ICAR ਅਤੇ PAU ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼',
      'field_inspection': 'ਨਿਗਰਾਨੀ ਅਤੇ ਪੱਤਾ ਜਾਂਚ',
      'field_inspection_desc': 'ਕੁੰਗੀ ਜਾਂ ਕੀੜਿਆਂ ਦੇ ਸ਼ੁਰੂਆਤੀ ਲੱਛਣਾਂ ਲਈ ਪੱਤਿਆਂ ਦੀ ਨਿਯਮਿਤ ਜਾਂਚ ਕਰੋ।',
      'irrigation_mgmt': 'ਸਿੰਚਾਈ ਪ੍ਰਬੰਧਨ',
      'irrigation_mgmt_desc': 'ਸ਼ਾਖਾਵਾਂ ਫੁੱਟਣ ਵੇਲੇ ਖੇਤ ਵਿੱਚ ਨਮੀ ਦਾ ਸਹੀ ਪੱਧਰ ਬਣਾ ਕੇ ਰੱਖੋ।',
      'bio_mgmt': 'ਬਚਾਅ ਅਤੇ ਜੈਵਿਕ ਉਪਚਾਰ',
      'bio_mgmt_desc': 'ਸਵੇਰ ਵੇਲੇ ਸਿਫ਼ਾਰਸ਼ੀ ਟ੍ਰਾਈਕੋਡਰਮਾ ਜਾਂ ਜੈਵਿਕ ਉੱਲੀਨਾਸ਼ਕ ਦਾ ਛਿੜਕਾਅ ਕਰੋ।',
      'kvk_helpline': 'KVK ਹੈਲਪਲਾਈਨ',
      'kvk_helpline_sub': 'ਖੇਤੀ ਵਿਗਿਆਨੀਆਂ ਤੋਂ ਸਿੱਧੀ ਸਲਾਹ: 1800-180-1551',
      'understood': 'ਠੀਕ ਹੈ',
      'days_together': 'ਨਾਲ {days} ਦਿਨ 🌱',
      'icar_advisory': 'ICAR ਸਲਾਹ',
      'summary_heading': 'ਖੇਤ ਅਤੇ ਫ਼ਸਲ ਸਿਹਤ ਸਾਰ',
      'good_morning': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
      'good_afternoon': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
      'good_evening': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
      'farmer': 'ਕਿਸਾਨ ਵੀਰ',
      'verified_farmer_account': 'ਪ੍ਰਮਾਣਿਤ ਕਿਸਾਨ ਖਾਤਾ',
      'sign_out_confirm_title': 'ਸਾਈਨ ਆਊਟ ਕਰੋ?',
      'sign_out_confirm_msg': 'ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਆਪਣੇ ਖਾਤੇ ਵਿੱਚੋਂ ਸਾਈਨ ਆਊਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'ai_server_lan': 'AI ਸਰਵਰ ਸਥਿਤੀ (LAN)',
      'online': 'ਆਨਲਾਈਨ',
      'offline': 'ਬੰਦ',
      'latitude_label': 'ਅਕਸ਼ਾਂਸ਼ (Lat)',
      'longitude_label': 'ਰੇਖਾਂਸ਼ (Lng)',
      'invalid_lat': 'ਗ਼ਲਤ ਅਕਸ਼ਾਂਸ਼ (-90 ਤੋਂ 90)',
      'invalid_lng': 'ਗ਼ਲਤ ਰੇਖਾਂਸ਼ (-180 ਤੋਂ 180)',
      'locate_farm_coords': 'ਖੇਤ ਨਿਰਦੇਸ਼ਾਂਕ ਖੋਜੋ',
      'point_location': 'ਬਿੰਦੂ ਸਥਾਨ (ਹੱਦ ਨਹੀਂ ਬਣਾਈ ਗਈ)',
      'active_farm_details': 'ਸਰਗਰਮ ਖੇਤ ਵੇਰਵਾ',
      'no_saved_farms': 'ਕੋਈ ਸੁਰੱਖਿਅਤ ਖੇਤ ਨਹੀਂ ਮਿਲਿਆ',
      'save_farm_first': 'ਵਿਸ਼ਲੇਸ਼ਣ ਦੇਖਣ ਲਈ ਪਹਿਲਾਂ ਹੋਮ ਸਕ੍ਰੀਨ ਤੇ ਖੇਤ ਚੁਣੋ ਅਤੇ ਸੇਵ ਕਰੋ।',
      'insights_trends': 'ਫ਼ਸਲ ਜਾਣਕਾਰੀ ਅਤੇ ਰੁਝਾਨ',
      'days_filter_7': '7 ਦਿਨ',
      'days_filter_30': '30 ਦਿਨ',
      'days_filter_all': 'ਸਾਰਾ ਸਮਾਂ',
      'swint_vision_result': 'Swin-T ਪਛਾਣ ਨਤੀਜਾ',
      'swint_neural_analysis': 'ਪੱਤਾ ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜਾ',
      'wheat_disease_diagnosis': 'ਕਣਕ ਰੋਗ ਨਿਦਾਨ (Swin-T)',
      'diagnosis': 'ਰੋਗ ਪਛਾਣ',
      'ppo_decision': 'ਫ਼ੈਸਲਾ',
      'standard_management': 'ਆਮ ਪ੍ਰਬੰਧਨ',
      'kvk_consultation': 'ਖੇਤੀਬਾੜੀ ਵਿਗਿਆਨੀਆਂ ਨਾਲ ਸਲਾਹ ਮਸ਼ਵਰਾ ਕਰੋ।',
      'get_verified_guidance': 'ਸਲਾਹ ਲਵੋ (Get Guidance)',
    },
    'bn': {
      'field_crop_summary': 'জমি ও ফসলের স্বাস্থ্য সারাংশ',
      'satellite_weather_favorable': 'উপগ্রহ ও আবহাওয়া সূচক অনুকূল রয়েছে।',
      'radar_backscatter': 'রাডার ব্যাকস্ক্যাটার',
      'confidence_short': 'সঠিকতা',
      'field_map': 'জমির মানচিত্র',
      'farm_map_instruction': 'মানচিত্রে সীমানা আঁকুন বা GPS দিয়ে জমি খুঁজুন',
      'processing_radar_weather': 'আবহাওয়া ও রাডার ডেটা বিশ্লেষণ করা হচ্ছে...',
      'irrigation_decision_footnote': 'আবহাওয়া এবং সেন্টিনেল-১ উপগ্রহ তথ্যের ভিত্তিতে সিদ্ধান্ত।',
      'feedback_title': 'নভকৃষিকে উন্নত করতে সাহায্য করুন',
      'feedback_subtitle': 'আমাদের সেচ ও ফসলের পরামর্শ কতটা কার্যকরী? মতামত দিন।',
      'farmer_feedback_form': 'কৃষক প্রতিক্রিয়া ফরম',
      'comments_hint': 'আপনার অভিজ্ঞতা বা পরামর্শ জানান...',
      'submitting': 'জমা হচ্ছে...',
      'feedback_thanks': 'ধন্যবাদ! আপনার প্রতিক্রিয়া নভকৃষিকে কৃষকদের জন্য আরো উন্নত করবে।',
      'welcome_title': 'নভকৃষিতে স্বাগতম',
      'reset_password': 'পাসওয়ার্ড রিসেট করুন',
      'welcome_subtitle': 'আপনার চাষাবাদ, আমাদের সাথে আরও স্মার্ট।',
      'join_subtitle': 'নভকৃষি পরিবারে যোগ দিতে বিবরণ পূরণ করুন।',
      'reset_subtitle': 'পাসওয়ার্ড লিঙ্কের জন্য নিবন্ধিত ইমেল দিন।',
      'trace_boundary_instruction': 'আপনার জমির চারপাশের সীমানা টানুন',
      'confirm_farm': 'জমি নিশ্চিত করুন',
      'boundary_confirmed': 'জমির সীমানা নিশ্চিত হয়েছে',
      'edit': 'সম্পাদনা',
      'latitude': 'অক্ষাংশ (Lat)',
      'longitude': 'দ্রাঘিমাংশ (Lng)',
      'locate_farm': 'জমি খুঁজুন',
      'insights_analytics': 'ফসলের বিশ্লেষণ ও ট্রেন্ড',
      'insights_subtitle': 'সেচ সুপারিশ এবং আর্দ্রতা ইতিহাস',
      'filter_7d': '৭ দিন',
      'filter_30d': '৩০ দিন',
      'filter_all': 'সব',
      'field_label': 'জমি',
      'use_my_location': 'আমার অবস্থান ব্যবহার করুন',
      'select_farm_area': 'জমির এলাকা নির্বাচন করুন',
      'draw_instruction': 'জমির সীমানা আঁকতে মানচিত্রে আলতো চাপুন।',
      'clear_boundary': 'এলাকা মুছুন',
      'confirm_location': 'জমির এলাকা নিশ্চিত করুন',
      'confirm_farm_location': 'জমির অবস্থান নিশ্চিত করুন',
      'weather_section': 'আবহাওয়ার অবস্থা',
      'temperature': 'তাপমাত্রা',
      'humidity': 'আর্দ্রতা',
      'rainfall_7d': 'বৃষ্টিপাত (গত ৭ দিন)',
      'rainfall_14d': 'বৃষ্টিপাত (গত ১৪ দিন)',
      'et0_7d': 'ET0 (পানির চাহিদা)',
      'deficit_7d': 'পানির ঘাটতি',
      'field_condition': 'মাটি / জমির অবস্থা',
      'estimated_water_condition': 'আনুমানিক জমির পানির অবস্থা',
      'low_stress': 'কম পানির চাপ',
      'moderate_requirement': 'মাঝারি পানির চাহিদা',
      'high_deficit': 'উচ্চ পানির ঘাটতি',
      'satellite_section': 'সেন্টিনেল-১ স্যাটেলাইট তথ্য',
      'vv_mean': 'VV গড়',
      'vv_change': 'VV পরিবর্তন',
      'observation_age': 'সর্বশেষ পর্যবেক্ষণের সময়',
      'satellite_freshness': 'স্যাটেলাইট ডেটা {days} দিন আগে আপডেট করা হয়েছে।',
      'more_details': 'আরও বিবরণ',
      'irrigation_recommendation': 'সেচের সুপারিশ',
      'apply_irrigation': '{amount} মিমি সেচ দিন',
      'no_irrigation': 'সেচের প্রয়োজন নেই',
      'explanation_title': 'এই সুপারিশ কেন?',
      'loading_gps': 'অবস্থান খোঁজা হচ্ছে...',
      'connecting_to_nabhkrishi': 'নভকৃষির সাথে সংযুক্ত হচ্ছে...',
      'fetching_weather_satellite': 'আবহাওয়া ও স্যাটেলাইট ডেটা আনা হচ্ছে...',
      'loading_weather': 'আবহাওয়ার তথ্য লোড হচ্ছে...',
      'loading_satellite': 'স্যাটেলাইট ডেটা লোড হচ্ছে...',
      'loading_analysis': 'জমির অবস্থা বিশ্লেষণ করা হচ্ছে...',
      'loading_recommendation': 'সেচের সুপারিশ তৈরি হচ্ছে...',
      'loading_cold_start': 'নভকৃষি পরিষেবা চালু হচ্ছে...',
      'error_title': 'কিছু ভুল হয়েছে',
      'error_gps_denied': 'অবস্থানের অনুমতি প্রত্যাখ্যান করা হয়েছে। GPS চালু করুন।',
      'error_gps_unavailable': 'আপনার ডিভাইসে অবস্থান পরিষেবা বন্ধ রয়েছে।',
      'error_502': 'স্যাটেলাইট ডেটা সাময়িকভাবে অনুপলব্ধ।',
      'error_generic': 'সংযোগ ত্রুটি। দয়া করে আবার চেষ্টা করুন।',
      'retry_button': 'আবার চেষ্টা করুন',
      'prediction_coordinate': 'আনুমানিক স্থানাঙ্ক',
      'farm_boundary': 'জমির সীমানা',
      'centroid_hint': 'অনুমান আপনার নির্বাচিত এলাকার কেন্দ্রের ওপর ভিত্তি করে।',
      'insufficient_points': 'আপনার জমির সীমানা চিহ্নিত করতে মানচিত্রে অন্তত ৩টি বিন্দু চাপুন।',
      'start_drawing': 'জমির সীমানা আঁকুন',
      'undo_point': 'পূর্বাবস্থায় ফেরান',
      'confirm_farm_area': 'জমির এলাকা নিশ্চিত করুন',
      'farm_area': 'জমির আয়তন',
      'hectares': 'হেক্টর',
      'save_farm': 'জমি সংরক্ষণ করুন',
      'phone_sign_in_title': 'মোবাইল নম্বর লিখুন',
      'phone_sign_in_subtitle': 'ফোন যাচাই করার জন্য আমরা একটি ৬-সংখ্যার OTP পাঠাব।',
      'or_continue_with': 'অথবা এর সাথে এগিয়ে যান',
      'continue_phone': 'ফোনের সাথে এগিয়ে যান',
      'continue_google': 'গুগলের সাথে এগিয়ে যান',
      'enter_phone': 'মোবাইল নম্বর লিখুন',
      'enter_otp': '৬-সংখ্যার OTP লিখুন',
      'resend_otp': 'OTP আবার পাঠান',
      'resend_in': 'আবার পাঠান',
      'verify_otp': 'যাচাই করে এগিয়ে যান',
      'error_invalid_phone': 'দয়া করে একটি সঠিক ১০-সংখ্যার মোবাইল নম্বর লিখুন।',
      'error_invalid_otp': 'দয়া করে ৬-সংখ্যার OTP লিখুন।',
      'error_google_sign_in': 'গুগল সাইন-ইন ব্যর্থ হয়েছে।',
      'error_otp_failed': 'OTP যাচাইকরণ ব্যর্থ হয়েছে। কোডটি পরীক্ষা করুন।',
      'logout_button': 'সাইন আউট',
      'sign_in': 'সাইন ইন',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'email_label': 'ইমেল ঠিকানা',
      'password_label': 'পাসওয়ার্ড',
      'confirm_password_label': 'পাসওয়ার্ড নিশ্চিত করুন',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'already_have_account': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
      'name_label': 'পুরো নাম',
      'error_invalid_email': 'দয়া করে একটি বৈধ ইমেল ঠিকানা দিন।',
      'error_weak_password': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
      'error_passwords_mismatch': 'পাসওয়ার্ড মিলছে না।',
      'error_user_not_found': 'এই ইমেলের সাথে কোনো অ্যাকাউন্ট পাওয়া যায়নি।',
      'error_wrong_password': 'ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।',
      'error_email_in_use': 'এই ইমেলটি ইতিমধ্যে নিবন্ধিত।',
      'nav_home': 'হোম',
      'nav_insights': 'বিশ্লেষণ',
      'nav_scan': 'স্ক্যান',
      'nav_farm': 'জমি',
      'nav_chat': 'নভ AI',
      'farmer_profile': 'কৃষক প্রোফাইল',
      'account_settings': 'অ্যাকাউন্টের বিবরণ ও সেটিংস',
      'active_farm_location': 'সক্রিয় জমির অবস্থান',
      'coordinates': 'স্থানাঙ্ক',
      'farm_area_label': 'জমির আয়তন',
      'language_preference': 'ভাষা পছন্দ',
      'verified_farmer': 'যাচাইকৃত কৃষক',
      'my_wheat_field': 'আমার গমের জমি',
      'my_farm': 'আমার জমি',
      'field_health': 'জমির স্বাস্থ্য',
      'satellite_view': 'স্যাটেলাইট ভিউ',
      'satellite_field_scan': 'স্যাটেলাইট জমি স্ক্যান',
      'scan_wheat': 'গম স্ক্যান করুন',
      'ask_nabh': 'নভ-কে জিজ্ঞাসা করুন',
      'recenter': 'পুনরায় কেন্দ্র করুন',
      'field_status': 'জমির অবস্থা',
      'crop_stage': 'ফসলের পর্যায়',
      'latest_scan': 'সর্বশেষ স্ক্যান',
      'recommended_action': 'প্রস্তাবিত পদক্ষেপ',
      'scanning': 'স্ক্যান হচ্ছে...',
      'demo_field': 'ডেমো জমি',
      'prototype_satellite_view': 'প্রোটোটাইপ স্যাটেলাইট ভিউ',
      'no_recent_scan': 'কোনো সাম্প্রতিক AI স্ক্যান নেই',
      'no_recent_recommendation': 'কোনো সাম্প্রতিক AI সুপারিশ নেই',
      'confidence_label': 'নির্ভুলতা (Confidence)',
      'confidence_disclaimer': 'নির্ভুলতা AI মডেলের স্বীকৃতির সম্ভাবনা নির্দেশ করে, রোগের তীব্রতা নয়।',
      'view_insights': 'বিশ্লেষণ দেখুন',
      'field_selector': 'জমি নির্বাচন',
      'wheat_crop': 'গম (Triticum aestivum)',
      'tillering_stage': 'কুশি পর্যায় (Tillering)',
      'sentinel_sar_band': 'সেন্টিনেল-১ সার রাডার ৫.৪GHz',
      'vv_polarization': 'VV পোলারাইজেশন',
      'tap_sector_hint': 'জমির অংশ: R1-R4 (নির্বাচন করতে ট্যাপ করুন)',
      'radar_signals': 'রাডার সিগন্যাল',
      'biomass_shift': 'বায়োমাস পরিবর্তন',
      'sentinel_age': 'সেন্টিনেল সময়',
      'demo_sar_disclaimer': 'প্রোটোটাইপ স্যাটেলাইট ভিউ (ডেমো SAR ডেটা) • প্রকৃত অরবিটাল টেলিমেট্রি নয়',
      'mark_your_farm': 'আপনার জমি চিহ্নিত করুন',
      'draw_farm_boundary_subtitle': 'মানচিত্রে আপনার জমির সীমানা আঁকুন',
      'draw_farm_boundary': 'জমির সীমানা আঁকুন',
      'my_location': 'আমার অবস্থান',
      'trace_around_boundary': 'আপনার জমির সীমানার চারপাশে আঙুল দিয়ে রেখা আঁকুন',
      'clear': 'মুছুন',
      'done': 'সম্পন্ন',
      'confirm_farm_boundary': 'জমির সীমানা নিশ্চিত করুন',
      'redraw': 'পুনরায় আঁকুন',
      'redraw_boundary': 'সীমানা পুনরায় আঁকুন',
      'confirm': 'নিশ্চিত করুন',
      'farm_boundary_saved': 'জমির সীমানা সংরক্ষিত হয়েছে',
      'acres': 'একর',
      'please_trace_boundary': 'অনুগ্রহ করে আপনার জমির সীমানা ঘিরে রেখা টানুন।',
      'location_unavailable': 'অবস্থান পাওয়া যায়নি। জিপিএস পরীক্ষা করুন।',
      'location_permission_denied': 'অবস্থানের অনুমতি প্রত্যাখ্যান করা হয়েছে।',
      'getting_your_location': 'অবস্থান খোঁজা হচ্ছে...',
      'quick_actions': 'দ্রুত পদক্ষেপ',
      'scan_leaf': 'পাতা স্ক্যান',
      'ask_nabh_chat': 'নভ চ্যাট',
      'field_map_action': 'জমির মানচিত্র',
      'current_status': 'বর্তমান ফসলের অবস্থা',
      'wheat_optimal': 'গম (স্বাভাবিক বৃদ্ধি)',
      'satellite_radar_safe': 'স্যাটেলাইট রাডার ও পানির সূচক অনুকূল।',
      'scan_foliage_link': 'পাতা স্ক্যান করুন →',
      'water_demand': 'পানির চাহিদা',
      'low_stress_short': 'কম চাপ',
      'rainfall_7d_short': '৭-দিনের বৃষ্টি',
      'adequate': 'পর্যাপ্ত',
      'sar_backscatter': 'রাডার ব্যাকস্ক্যাটার',
      'avg_temp': 'গড় তাপমাত্রা',
      'normal': 'স্বাভাবিক',
      'recent_foliage_diagnosis': 'সাম্প্রতিক ফসল রোগ নির্ণয়',
      'ai_management_decision': 'AI ব্যবস্থাপনা সিদ্ধান্ত',
      'decision_context_footnote': 'শনাক্তকৃত রোগ, নির্ভুলতা, ফসলের পর্যায় এবং জমির প্রেক্ষাপটের ওপর ভিত্তি করে।',
      'get_guidance': 'পরামর্শ নিন (Ask Nabh)',
      'recheck_photo': 'স্পষ্ট ছবি তুলুন',
      'detected_class': 'শনাক্তকৃত শ্রেণি',
      'image_analyzed': 'বিশ্লেষণ সম্পন্ন',
      'close': 'বন্ধ করুন',
      'cancel': 'বাতিল করুন',
      'submit': 'জমা দিন',
      'feedback_help': 'নভকৃষিকে আরও উন্নত করতে সাহায্য করুন',
      'feedback_sub': 'আমাদের সুপারিশগুলি আপনার জন্য কতটা কার্যকর?',
      'give_feedback': 'মতামত দিন',
      'feedback_submitted': 'মতামত জমা দেওয়া হয়েছে!',
      'farmer_feedback': 'কৃষক প্রতিক্রিয়া ফর্ম',
      'select_rating': 'রেটিং দিন:',
      'comments_optional': 'মন্তব্য (ঐচ্ছিক):',
      'feedback_hint': 'আপনার মতামত এখানে লিখুন...',
      'weather_modal_title': 'আবহাওয়া ও বৃষ্টি রাডার',
      'weather_modal_subtitle': 'স্থানভিত্তিক পূর্বাভাস',
      'wind_speed': 'বাতাসের গতি',
      'rain_chance': 'বৃষ্টির সম্ভাবনা',
      'met_advice_title': 'কৃষি আবহাওয়া পরামর্শ',
      'met_advice_body': 'পরবর্তী ৪৮ ঘণ্টায় ভারী বৃষ্টির সম্ভাবনা কম। পাতায় স্প্রে বা সেচ দেওয়া যেতে পারে।',
      'agronomic_advisory_title': 'ফসল সুরক্ষা পরামর্শ',
      'agronomic_advisory_subtitle': 'ICAR ও বিশ্ববিদ্যালয় নির্দেশিকা',
      'field_inspection': 'নিয়মিত পর্যবেক্ষণ',
      'field_inspection_desc': 'মরিচা বা পোকার প্রাথমিক লক্ষণ যাচাই করতে পাতার নিচের অংশ নিয়মিত পর্যবেক্ষণ করুন।',
      'irrigation_mgmt': 'সেচ ব্যবস্থাপনা',
      'irrigation_mgmt_desc': 'কুশি বের হওয়ার সময় জমিতে প্রয়োজনীয় আর্দ্রতা বজায় রাখুন।',
      'bio_mgmt': 'প্রতিরোধ ও জৈব ব্যবস্থা',
      'bio_mgmt_desc': 'সকালের দিকে ট্রাইকোডার্মা বা অনুমোদিত জৈব ছত্রাকনাশক স্প্রে করুন।',
      'kvk_helpline': 'কেভিকে হেল্পলাইন',
      'kvk_helpline_sub': 'টোল-ফ্রি কৃষি বিশেষজ্ঞ সহায়তা: 1800-180-1551',
      'understood': 'বুঝেছি',
      'days_together': 'একসাথে {days} দিন 🌱',
      'icar_advisory': 'ICAR পরামর্শ',
      'summary_heading': 'জমি ও ফসলের স্বাস্থ্য সারসংক্ষেপ',
      'good_morning': 'শুভ সকাল',
      'good_afternoon': 'শুভ অপরাহ্ন',
      'good_evening': 'শুভ সন্ধ্যা',
      'farmer': 'কৃষক ভাই',
      'verified_farmer_account': 'যাচাইকৃত কৃষক অ্যাকাউন্ট',
      'sign_out_confirm_title': 'সাইন আউট করবেন?',
      'sign_out_confirm_msg': 'আপনি কি নিশ্চিত যে আপনি আপনার অ্যাকাউন্ট থেকে সাইন আউট করতে চান?',
      'ai_server_lan': 'AI সার্ভার অবস্থা (LAN)',
      'online': 'অনলাইন',
      'offline': 'অফলাইন',
      'latitude_label': 'অক্ষাংশ (Lat)',
      'longitude_label': 'দ্রাঘিমাংশ (Lng)',
      'invalid_lat': 'ভুল অক্ষাংশ (-৯০ থেকে ৯০)',
      'invalid_lng': 'ভুল দ্রাঘিমাংশ (-১৮০ থেকে ১৮০)',
      'locate_farm_coords': 'জমির স্থানাঙ্ক খুঁজুন',
      'point_location': 'বিন্দু অবস্থান (সীমানা চিহ্নিত নয়)',
      'active_farm_details': 'সক্রিয় জমির বিবরণ',
      'no_saved_farms': 'কোনো সংরক্ষিত জমি পাওয়া যায়নি',
      'save_farm_first': 'বিশ্লেষণ দেখতে প্রথমে হোম স্ক্রিনে জমি চিহ্নিত করে সংরক্ষণ করুন।',
      'insights_trends': 'ফসল বিশ্লেষণ ও প্রবণতা',
      'days_filter_7': '৭ দিন',
      'days_filter_30': '৩০ দিন',
      'days_filter_all': 'সব সময়',
      'swint_vision_result': 'Swin-T ফলাফল',
      'swint_neural_analysis': 'পাতা বিশ্লেষণ ফলাফল',
      'wheat_disease_diagnosis': 'গমের রোগ নির্ণয় (Swin-T)',
      'diagnosis': 'রোগ নির্ণয়',
      'ppo_decision': 'সিদ্ধান্ত',
      'standard_management': 'সাধারণ ব্যবস্থাপনা',
      'kvk_consultation': 'উদ্ভিদ রোগ বিশেষজ্ঞের পরামর্শ নিন।',
      'get_verified_guidance': 'পরামর্শ নিন (Get Guidance)',
    },
    'hr': {
      'field_crop_summary': 'खेत अर फसल सेहत सारांश',
      'satellite_weather_favorable': 'उपग्रह अर मौसम के आंकड़े सही सैं।',
      'radar_backscatter': 'रडार बैकस्कैटर',
      'confidence_short': 'सटीकता',
      'field_map': 'खेत का नक्शा',
      'farm_map_instruction': 'नक्शे पै सीमा खींचो या GPS तै खेत टटोलो',
      'processing_radar_weather': 'मौसम अर रडार का हिसाब लग रह्या सै...',
      'irrigation_decision_footnote': 'मौसम अर सेंटिनल-1 उपग्रह पै आधारित पक्का निर्णय।',
      'feedback_title': 'नभकृषि नै और बढ़िया बणाण खातर राय द्यो',
      'feedback_subtitle': 'म्हारी सलाह थारे कितणी काम आई? अपनी बात बताओ।',
      'farmer_feedback_form': 'किसान राय फॉर्म',
      'comments_hint': 'थारा अनुभव या सुझाव सांझा करो...',
      'submitting': 'भेजी जावै सै...',
      'feedback_thanks': 'घणा धन्यवाद! थारी राय तै नभकृषि और बढ़िया बणेगी।',
      'welcome_title': 'नभकृषि में थारा स्वागत सै',
      'reset_password': 'पासवर्ड बदलो',
      'welcome_subtitle': 'थारी खेती, म्हारे साथे और समझदार।',
      'join_subtitle': 'नभकृषि तै जुड़ण खातर फॉर्म भरो।',
      'reset_subtitle': 'पासवर्ड लिंक खातर अपणी ईमेल लिखो।',
      'trace_boundary_instruction': 'अपणे खेत की मेढ़ पै लकीर खींचो',
      'confirm_farm': 'खेत पक्का करो',
      'boundary_confirmed': 'खेत की मेढ़ पक्की हो गी',
      'edit': 'बदलो',
      'latitude': 'अक्षांश (Lat)',
      'longitude': 'देशांतर (Lng)',
      'locate_farm': 'खेत ढूंढो',
      'insights_analytics': 'फसल की पड़ताल व रुझान',
      'insights_subtitle': 'पाणी की सलाह अर नमी का हिसाब',
      'filter_7d': '7 दिन',
      'filter_30d': '30 दिन',
      'filter_all': 'सारे',
      'field_label': 'खेत',
      'use_my_location': 'म्हारी लोकेशन लेओ',
      'select_farm_area': 'खेत का इलाका चुणो',
      'draw_instruction': 'खेत की मेढ़ बणाण खातर नक्शे पै उंगली टेक्यो।',
      'clear_boundary': 'इलाका साफ करो',
      'confirm_location': 'खेत का इलाका पक्का करो',
      'confirm_farm_location': 'खेत की जगह पक्की करो',
      'weather_section': 'मौसम का हाल',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'rainfall_7d': 'मींह (पाछले 7 दिन)',
      'rainfall_14d': 'मींह (पाछले 14 दिन)',
      'et0_7d': 'ET0 (पाणी की जरूरत)',
      'deficit_7d': 'पाणी की कमी',
      'field_condition': 'माटी / खेत की हालत',
      'estimated_water_condition': 'खेत में पाणी की हालत',
      'low_stress': 'पाणी की कम चिंता',
      'moderate_requirement': 'सामान्य पाणी की जरूरत',
      'high_deficit': 'पाणी की घणी कमी',
      'satellite_section': 'सेंटिनल-1 सैटेलाइट जानकारी',
      'vv_mean': 'VV मीन',
      'vv_change': 'VV बदलाव',
      'observation_age': 'ताजा देखने का बखत',
      'satellite_freshness': 'सैटेलाइट डेटा {days} दिन पैहल्यां आया था।',
      'more_details': 'और जानकारी',
      'irrigation_recommendation': 'पाणी (सिंचाई) की सलाह',
      'apply_irrigation': '{amount} मिमी पाणी लगाओ',
      'no_irrigation': 'इब पाणी लाण की जरूरत कोन्या',
      'explanation_title': 'या सलाह क्यूं?',
      'loading_gps': 'लोकेशन ढूंढी जा रही सै...',
      'connecting_to_nabhkrishi': 'नाभकृषि तै जुड़ रह्या सै...',
      'fetching_weather_satellite': 'मौसम अर सैटेलाइट का हाल ले रहे सां...',
      'loading_weather': 'मौसम का हाल आ रह्या सै...',
      'loading_satellite': 'सैटेलाइट डेटा आ रह्या सै...',
      'loading_analysis': 'खेत की जांच हो रही सै...',
      'loading_recommendation': 'सिंचाई की सलाह बणा रहे सां...',
      'loading_cold_start': 'नाभकृषि सेवा चालू हो रही सै...',
      'error_title': 'किमे गड़बड़ होगी',
      'error_gps_denied': 'लोकेशन की छूट कोन्या मिली। GPS ऑन करो।',
      'error_gps_unavailable': 'फोन में लोकेशन बंद पड़ी सै।',
      'error_502': 'सैटेलाइट डेटा इब मिल कोन्या रह्या।',
      'error_generic': 'कनेक्शन में दिक्कत सै। दोबारा करके देख्यो।',
      'retry_button': 'दोबारा करो',
      'prediction_coordinate': 'अनुमानित ठिकाणा',
      'farm_boundary': 'खेत की मेढ़',
      'centroid_hint': 'सलाह थारे खेत के बीचले हिस्से के हिसाब तै सै।',
      'insufficient_points': 'खेत बणाण खातर नक्शे पै कम तै कम 3 जगह दबाओ।',
      'start_drawing': 'खेत की मेढ़ बणाओ',
      'undo_point': 'पाछै हटो',
      'confirm_farm_area': 'खेत पक्का करो',
      'farm_area': 'खेत का रकबा',
      'hectares': 'हेक्टेयर',
      'save_farm': 'खेत सहेजो',
      'phone_sign_in_title': 'मोबाइल नंबर भरो',
      'phone_sign_in_subtitle': 'फोन जांचण खातर 6 अंक का OTP भेजेंगे।',
      'or_continue_with': 'या इसके गैल चालो',
      'continue_phone': 'फोन तै आगे चालो',
      'continue_google': 'गूगल तै आगे चालो',
      'enter_phone': 'मोबाइल नंबर भरो',
      'enter_otp': '6 अंक का OTP भरो',
      'resend_otp': 'OTP फेर तै भेजो',
      'resend_in': 'फेर तै भेजो',
      'verify_otp': 'जांचो अर आगे चालो',
      'error_invalid_phone': '10 अंक का सही मोबाइल नंबर भरो।',
      'error_invalid_otp': '6 अंक का OTP भरो।',
      'error_google_sign_in': 'गूगल लॉगिन कोन्या होया।',
      'error_otp_failed': 'OTP गलत सै। दोबारा देख्यो।',
      'logout_button': 'लॉग आउट',
      'sign_in': 'साइन इन',
      'create_account': 'खाता बणाओ',
      'email_label': 'ईमेल पता',
      'password_label': 'पासवर्ड',
      'confirm_password_label': 'पासवर्ड दोबारा भरो',
      'forgot_password': 'पासवर्ड भूल गे?',
      'dont_have_account': 'खाता कोन्या?',
      'already_have_account': 'पहल्यां तै खाता सै?',
      'name_label': 'पूरा नाम',
      'error_invalid_email': 'सही ईमेल पता भरो।',
      'error_weak_password': 'पासवर्ड कम तै कम 6 अक्षर का होणा चाहिए।',
      'error_passwords_mismatch': 'पासवर्ड मेल कोन्या खांदे।',
      'error_user_not_found': 'इस ईमेल पै कोई खाता कोन्या मिल्या।',
      'error_wrong_password': 'गलत पासवर्ड। फेर कोशिश करो।',
      'error_email_in_use': 'या ईमेल पैहल्यां तै पंजीकृत सै।',
      'nav_home': 'घर',
      'nav_insights': 'पड़ताल',
      'nav_scan': 'जांच',
      'nav_farm': 'खेत',
      'nav_chat': 'नभ AI',
      'farmer_profile': 'किसान प्रोफाइल',
      'account_settings': 'खाता विवरण अर सेटिंग',
      'active_farm_location': 'चालू खेत का ठिकाणा',
      'coordinates': 'निर्देशांक',
      'farm_area_label': 'खेत का रकबा',
      'language_preference': 'बोली / भाषा',
      'verified_farmer': 'जांच्या होया किसान',
      'my_wheat_field': 'म्हारा गेहूं का खेत',
      'my_farm': 'म्हारा खेत',
      'field_health': 'खेत की हालत',
      'satellite_view': 'सैटेलाइट का नजारा',
      'satellite_field_scan': 'सैटेलाइट खेत जांच',
      'scan_wheat': 'गेहूं जांचो',
      'ask_nabh': 'नभ तै पूछो',
      'recenter': 'फेर बीच में ल्याओ',
      'field_status': 'खेत की स्थिति',
      'crop_stage': 'फसल की अवस्था',
      'latest_scan': 'ताजा जांच',
      'recommended_action': 'सलाह अर कदम',
      'scanning': 'जांच चालू सै...',
      'demo_field': 'डेमो खेत',
      'prototype_satellite_view': 'प्रोटोटाइप सैटेलाइट नजारा',
      'no_recent_scan': 'हाल में कोई AI जांच कोन्या',
      'no_recent_recommendation': 'हाल में कोई AI सलाह कोन्या',
      'confidence_label': 'सटीकता (Confidence)',
      'confidence_disclaimer': 'सटीकता AI मॉडल की पहचान की संभावना सै, बीमारी की गंभीरता कोन्या।',
      'view_insights': 'पड़ताल देखो',
      'field_selector': 'खेत चुणो',
      'wheat_crop': 'गेहूं (कणक)',
      'tillering_stage': 'फुटाव की अवस्था (Tillering)',
      'sentinel_sar_band': 'सेंटिनल-1 सार रडार 5.4GHz',
      'vv_polarization': 'VV ध्रुवीकरण',
      'tap_sector_hint': 'खेत के हिस्से: R1-R4 (चुणन खातर दबाओ)',
      'radar_signals': 'रडार सिग्नल्स',
      'biomass_shift': 'बायोमास बदलाव',
      'sentinel_age': 'सेंटिनल बखत',
      'demo_sar_disclaimer': 'प्रोटोटाइप सैटेलाइट नजारा (डेमो SAR डेटा) • असली आर्बिटल टेलीमेट्री कोन्या',
      'mark_your_farm': 'अपणे खेत पै निशान लाओ',
      'draw_farm_boundary_subtitle': 'नक्शे पै अपणे खेत की मेढ़ बणाओ',
      'draw_farm_boundary': 'खेत की मेढ़ बणाओ',
      'my_location': 'म्हारी लोकेशन',
      'trace_around_boundary': 'खेत की मेढ़ के चारे कान्नी उंगली तै लकीर खींचो',
      'clear': 'साफ करो',
      'done': 'हो गया',
      'confirm_farm_boundary': 'खेत की मेढ़ पक्की करो',
      'redraw': 'फेर तै बणाओ',
      'redraw_boundary': 'मेढ़ फेर तै बणाओ',
      'confirm': 'पक्का करो',
      'farm_boundary_saved': 'खेत की मेढ़ सहेज ली',
      'acres': 'एकड़',
      'please_trace_boundary': 'अपणे खेत की मेढ़ के चारे कान्नी लकीर खींचो।',
      'location_unavailable': 'लोकेशन कोन्या मिली। GPS जांचो।',
      'location_permission_denied': 'लोकेशन की छूट कोन्या मिली।',
      'getting_your_location': 'लोकेशन ढूंढी जा रही सै...',
      'quick_actions': 'तुरंत के काम',
      'scan_leaf': 'पत्ता जांच',
      'ask_nabh_chat': 'नभ बात',
      'field_map_action': 'खेत का नक्शा',
      'current_status': 'फसल का ताजा हाल',
      'wheat_optimal': 'गेहूं (बढ़िया बढ़वार)',
      'satellite_radar_safe': 'सैटेलाइट रडार अर पाणी का हाल ठीक सै।',
      'scan_foliage_link': 'पत्ता जांचो →',
      'water_demand': 'पाणी की जरूरत',
      'low_stress_short': 'कम खिंचाव',
      'rainfall_7d_short': '7-दिन का मींह',
      'adequate': 'घणा ठीक',
      'sar_backscatter': 'रडार बैकस्कैटर',
      'avg_temp': 'औसत तापमान',
      'normal': 'सामान्य',
      'recent_foliage_diagnosis': 'ताजा फसल पड़ताल',
      'ai_management_decision': 'AI सलाह फैसला',
      'decision_context_footnote': 'पहचाणी गई बीमारी, सटीकता, फसल की हालत अर खेत के हिसाब तै सलाह।',
      'get_guidance': 'सलाह लेओ (Ask Nabh)',
      'recheck_photo': 'फेर साफ फोटो खींचो',
      'detected_class': 'पहचाण्या होया नतीजा',
      'image_analyzed': 'जांच पूरी हुई',
      'close': 'बंद करो',
      'cancel': 'रद्द करो',
      'submit': 'जमा करो',
      'feedback_help': 'नभकृषि नै और बढ़िया बणाण में मदद करो',
      'feedback_sub': 'म्हारी सलाह थारे खातर कितनी काम आई?',
      'give_feedback': 'राय द्यो',
      'feedback_submitted': 'राय दर्ज होगी!',
      'farmer_feedback': 'किसान राय फॉर्म',
      'select_rating': 'रेटिंग चुणो:',
      'comments_optional': 'किमे लिखणा चाहो तो (वैकल्पिक):',
      'feedback_hint': 'अपणी राय उरे लिखो...',
      'weather_modal_title': 'मौसम अर मींह रडार',
      'weather_modal_subtitle': 'जगह का हाल',
      'wind_speed': 'हवा की चाल',
      'rain_chance': 'मींह का अनुमान',
      'met_advice_title': 'खेती मौसम सलाह',
      'met_advice_body': 'आगले 48 घंटे में भारी मींह की उम्मीद कोन्या। पत्ते पै स्प्रे या हलका पाणी दे सको सो।',
      'agronomic_advisory_title': 'फसल रक्षा सलाह',
      'agronomic_advisory_subtitle': 'कृषि विज्ञान केंद्र अर ICAR की सलाह',
      'field_inspection': 'निगरानी अर पत्ती की जांच',
      'field_inspection_desc': 'रतुआ या कीड़े के सुरुआती लक्षण खातर पत्ते की रोज देखभाल करो।',
      'irrigation_mgmt': 'पाणी का इंतजाम',
      'irrigation_mgmt_desc': 'फुटाव के टेम खेत में सही नमी बणाए राखो ताके जड़ पै जोर ना पड़े।',
      'bio_mgmt': 'रोकथाम अर जैविक उपाय',
      'bio_mgmt_desc': 'तड़कै-तड़कै ट्राइकोडर्मा या बढ़िया जैविक फफूंदनाशी का छिड़काव करो।',
      'kvk_helpline': 'KVK हेल्पलाइन',
      'kvk_helpline_sub': 'कृषि वैज्ञानिकां तै सीधी बात: 1800-180-1551',
      'understood': 'ठीक सै',
      'days_together': 'गैल {days} दिन 🌱',
      'icar_advisory': 'ICAR सलाह',
      'summary_heading': 'खेत अर फसल की हालत',
      'good_morning': 'राम राम',
      'good_afternoon': 'राम राम',
      'good_evening': 'राम राम',
      'farmer': 'किसान भाई',
      'verified_farmer_account': 'जांच्या होया किसान खाता',
      'sign_out_confirm_title': 'लॉग आउट करो?',
      'sign_out_confirm_msg': 'के थाम सच में लॉग आउट करणा चाहो सो?',
      'ai_server_lan': 'AI सर्वर हालत (LAN)',
      'online': 'चालू सै',
      'offline': 'बंद सै',
      'latitude_label': 'अक्षांश (Lat)',
      'longitude_label': 'देशांतर (Lng)',
      'invalid_lat': 'गलत अक्षांश (-90 तै 90)',
      'invalid_lng': 'गलत देशांतर (-180 तै 180)',
      'locate_farm_coords': 'खेत का ठिकाणा ढूंढो',
      'point_location': 'बिंदु ठिकाणा (मेढ़ कोन्या खींची)',
      'active_farm_details': 'चालू खेत का ब्योरा',
      'no_saved_farms': 'कोई खेत सहेज्या कोन्या',
      'save_farm_first': 'पड़ताल देखण खातर पैहल्यां होम स्क्रीन पै खेत चुणो अर सहेजो।',
      'insights_trends': 'फसल पड़ताल अर रुझान',
      'days_filter_7': '7 दिन',
      'days_filter_30': '30 दिन',
      'days_filter_all': 'सारा बखत',
      'swint_vision_result': 'पहचाण्या नतीजा (Swin-T)',
      'swint_neural_analysis': 'पत्ता जांच का नतीजा',
      'wheat_disease_diagnosis': 'गेहूं बीमारी जांच (Swin-T)',
      'diagnosis': 'रोग की पहचान',
      'ppo_decision': 'फैसला',
      'standard_management': 'साधारण सार संभाल',
      'kvk_consultation': 'कृषि वैज्ञानिकां तै सलाह लेओ।',
      'get_verified_guidance': 'सलाह लेओ (Get Guidance)',
    },
    'hinglish': {
      'field_crop_summary': 'Khet aur Fasal Health Summary',
      'satellite_weather_favorable': 'Satellite radar aur weather index anukool hain.',
      'radar_backscatter': 'SAR Backscatter',
      'confidence_short': 'satikta',
      'field_map': 'Khet Naksha',
      'farm_map_instruction': 'Map par tap karke boundary banayein ya khet search karein',
      'processing_radar_weather': 'Mausam aur radar telemetry analyze ho rahi hai...',
      'irrigation_decision_footnote': 'Active weather aur Sentinel-1 satellite data par aadharit safe decision.',
      'feedback_title': 'NabhKrishi ko behtar banane mein madad karein',
      'feedback_subtitle': 'Hamari recommendations aapke liye kitni useful hain? Feedback dein.',
      'farmer_feedback_form': 'Farmer Feedback Form',
      'comments_hint': 'Apna anubhav, suggestions ya zarooratein share karein...',
      'submitting': 'Bheja ja raha hai...',
      'feedback_thanks': 'Dhanyawad! Aapka feedback NabhKrishi ko kisanon ke liye aur behtar banayega.',
      'welcome_title': 'NabhKrishi mein Swagat Hai',
      'reset_password': 'Password Reset Karein',
      'welcome_subtitle': 'Aapki kheti, hamare sath aur smart.',
      'join_subtitle': 'NabhKrishi parivar ka hissa banne ke liye form bharein.',
      'reset_subtitle': 'Password reset link ke liye registered email dalein.',
      'trace_boundary_instruction': 'Apne khet ki boundary ke chaaron taraf line banayein',
      'confirm_farm': 'Khet Confirm Karein',
      'boundary_confirmed': 'Khet Boundary Confirm Ho Gayi',
      'edit': 'Edit',
      'latitude': 'Latitude (Lat)',
      'longitude': 'Longitude (Lng)',
      'locate_farm': 'Khet Locate Karein',
      'insights_analytics': 'Fasal Insights aur Trends',
      'insights_subtitle': 'Sinchai recommendations aur moisture history',
      'filter_7d': '7 Din',
      'filter_30d': '30 Din',
      'filter_all': 'Sabhi',
      'field_label': 'Khet',
      'use_my_location': 'Meri Location Use Karein',
      'select_farm_area': 'Khet Select Karein',
      'draw_instruction': 'Apne khet ki seema banane ke liye map par tap karein.',
      'clear_boundary': 'Area Clear Karein',
      'confirm_location': 'Khet Area Confirm Karein',
      'confirm_farm_location': 'Khet Ki Location Confirm Karein',
      'weather_section': 'Mausam Ki Sthiti',
      'temperature': 'Taapman',
      'humidity': 'Aardrata (Humidity)',
      'rainfall_7d': 'Barish (Pichle 7 Din)',
      'rainfall_14d': 'Barish (Pichle 14 Din)',
      'et0_7d': 'ET0 (Pani Ki Demand)',
      'deficit_7d': 'Pani Ki Kami',
      'field_condition': 'Mitti / Khet Ki Sthiti',
      'estimated_water_condition': 'Field Water Condition',
      'low_stress': 'Kam estimated water stress',
      'moderate_requirement': 'Samanya pani ki zaroorat',
      'high_deficit': 'Zyaada estimated water deficit',
      'satellite_section': 'Sentinel-1 Satellite Jankari',
      'vv_mean': 'VV Mean',
      'vv_change': 'VV Badlav',
      'observation_age': 'Taaza Observation Age',
      'satellite_freshness': 'Satellite data {days} din pehle update hua tha.',
      'more_details': 'Aur Jankari',
      'irrigation_recommendation': 'Sinchai Ki Salah',
      'apply_irrigation': '{amount} mm sinchai karein',
      'no_irrigation': 'Sinchai ki zaroorat nahi hai',
      'explanation_title': 'Ye salah kyu?',
      'loading_gps': 'Location dhoondhi ja rahi hai...',
      'connecting_to_nabhkrishi': 'NabhKrishi se connect ho raha hai...',
      'fetching_weather_satellite': 'Mausam aur satellite data liya ja raha hai...',
      'loading_weather': 'Mausam ki jankari aa rahi hai...',
      'loading_satellite': 'Satellite data fetch ho raha hai...',
      'loading_analysis': 'Khet ki sthiti analyze ho rahi hai...',
      'loading_recommendation': 'Sinchai salah banayi ja rahi hai...',
      'loading_cold_start': 'NabhKrishi services start ho rahi hain...',
      'error_title': 'Kuch gadbad hui',
      'error_gps_denied': 'Location permission denied. Kripya GPS on karein.',
      'error_gps_unavailable': 'Device par location service band hai.',
      'error_502': 'Satellite data temporary roop se band hai. Kripya thodi der baad try karein.',
      'error_generic': 'Connection error. Kripya dobara koshish karein.',
      'retry_button': 'Dobara Koshish Karein',
      'prediction_coordinate': 'Prediction Coordinate',
      'farm_boundary': 'Khet Ki Seema',
      'centroid_hint': 'Salah aapke chune huye khet ke center par based hai.',
      'insufficient_points': 'Khet mark karne ke liye map par kam se kam 3 points tap karein.',
      'start_drawing': 'Khet Ki Seema Banayein',
      'undo_point': 'Undo Karein',
      'confirm_farm_area': 'Khet Area Confirm Karein',
      'farm_area': 'Khet Ka Area',
      'hectares': 'hectares',
      'save_farm': 'Khet Save Karein',
      'phone_sign_in_title': 'Mobile Number Dalein',
      'phone_sign_in_subtitle': 'Aapke phone ko verify karne ke liye 6-digit OTP bhejenge.',
      'or_continue_with': 'Ya iske saath aage badhein',
      'continue_phone': 'Phone ke saath continue karein',
      'continue_google': 'Google ke saath continue karein',
      'enter_phone': 'Mobile Number Dalein',
      'enter_otp': '6-digit OTP Dalein',
      'resend_otp': 'OTP Dobara Bhejein',
      'resend_in': 'Dobara bhejein',
      'verify_otp': 'Verify & Aage Badhein',
      'error_invalid_phone': 'Kripya 10-digit sahi mobile number dalein.',
      'error_invalid_otp': 'Kripya 6-digit OTP dalein.',
      'error_google_sign_in': 'Google Sign-In fail ya cancel hua.',
      'error_otp_failed': 'OTP verification fail hua. Code check karein.',
      'logout_button': 'Sign Out',
      'sign_in': 'Sign In',
      'create_account': 'Account Banayein',
      'email_label': 'Email Address',
      'password_label': 'Password',
      'confirm_password_label': 'Confirm Password',
      'forgot_password': 'Password bhool gaye?',
      'dont_have_account': 'Account nahi hai?',
      'already_have_account': 'Pehle se account hai?',
      'name_label': 'Poora Naam',
      'error_invalid_email': 'Kripya valid email address dalein.',
      'error_weak_password': 'Password kam se kam 6 characters ka hona chahiye.',
      'error_passwords_mismatch': 'Passwords match nahi kar rahe.',
      'error_user_not_found': 'Is email se account nahi mila.',
      'error_wrong_password': 'Galat password. Dobara koshish karein.',
      'error_email_in_use': 'Ye email pehle se registered hai.',
      'nav_home': 'Home',
      'nav_insights': 'Insights',
      'nav_scan': 'Scan',
      'nav_farm': 'Khet',
      'nav_chat': 'Nabh AI',
      'farmer_profile': 'Kisan Profile',
      'account_settings': 'Account details aur preferences',
      'active_farm_location': 'Active Khet Location',
      'coordinates': 'Coordinates',
      'farm_area_label': 'Khet Area',
      'language_preference': 'Bhasha Preference',
      'verified_farmer': 'Verified Kisan',
      'my_wheat_field': 'Mera Gehun Ka Khet',
      'my_farm': 'Mera Khet',
      'field_health': 'Khet Ki Health',
      'satellite_view': 'Satellite View',
      'satellite_field_scan': 'Satellite Khet Scan',
      'scan_wheat': 'Gehun Scan Karein',
      'ask_nabh': 'Nabh Se Poochhein',
      'recenter': 'Recenter',
      'field_status': 'Khet Ki Sthiti',
      'crop_stage': 'Fasal Stage',
      'latest_scan': 'Latest Scan',
      'recommended_action': 'Sifarish Kiya Gaya Kadam',
      'scanning': 'Scanning chal rahi hai...',
      'demo_field': 'Demo Khet',
      'prototype_satellite_view': 'Prototype Satellite View',
      'no_recent_scan': 'Haal hi mein koi AI scan nahi',
      'no_recent_recommendation': 'Haal hi mein koi AI sifarish nahi',
      'confidence_label': 'Confidence (Sateekta)',
      'confidence_disclaimer': 'Confidence AI model ki pehchan sambhavna hai, bimari ki severity nahi.',
      'view_insights': 'Insights Dekhein',
      'field_selector': 'Khet Selector',
      'wheat_crop': 'Gehun (Triticum aestivum)',
      'tillering_stage': 'Kalle Phootna (Tillering)',
      'sentinel_sar_band': 'SENTINEL-1 SAR 5.4GHz',
      'vv_polarization': 'VV POLARIZATION',
      'tap_sector_hint': 'Khet Sectors: R1-R4 (Chunne ke liye tap karein)',
      'radar_signals': 'Radar Signals',
      'biomass_shift': 'Biomass Shift',
      'sentinel_age': 'Sentinel Age',
      'demo_sar_disclaimer': 'Prototype Satellite View (Demo SAR Data) • Real-time orbital telemetry nahi',
      'mark_your_farm': 'Apna Khet Mark Karein',
      'draw_farm_boundary_subtitle': 'Map par apne khet ki seema banayein',
      'draw_farm_boundary': 'Khet Ki Seema Banayein',
      'my_location': 'Meri Location',
      'trace_around_boundary': 'Apne khet ki seema ke chaaro taraf ungli se line banayein',
      'clear': 'Clear',
      'done': 'Done',
      'confirm_farm_boundary': 'Khet Seema Confirm Karein',
      'redraw': 'Dobara Banayein',
      'redraw_boundary': 'Seema Dobara Banayein',
      'confirm': 'Confirm Karein',
      'farm_boundary_saved': 'Khet Ki Seema Save Ho Gayi',
      'acres': 'Acres',
      'please_trace_boundary': 'Kripya apne khet ki seema trace karein.',
      'location_unavailable': 'Location unavailable. GPS check karein.',
      'location_permission_denied': 'Location permission nahi mili.',
      'getting_your_location': 'Aapki location dhoondhi ja rahi hai...',
      'quick_actions': 'Quick Actions',
      'scan_leaf': 'Patti Scan',
      'ask_nabh_chat': 'Nabh Chat',
      'field_map_action': 'Khet Naksha',
      'current_status': 'Current Fasal Sthiti',
      'wheat_optimal': 'Gehun (Optimal)',
      'satellite_radar_safe': 'Satellite radar & water index safe zone mein hain.',
      'scan_foliage_link': 'Patti scan karein →',
      'water_demand': 'Pani Ki Mang',
      'low_stress_short': 'Kam stress',
      'rainfall_7d_short': '7-din Barish',
      'adequate': 'Paryapt',
      'sar_backscatter': 'SAR Backscatter',
      'avg_temp': 'Avg Temp',
      'normal': 'Normal',
      'recent_foliage_diagnosis': 'Haal hi ka Rog Nidan',
      'ai_management_decision': 'AI Management Decision',
      'decision_context_footnote': 'Pehchani gayi bimari, confidence, fasal avastha aur khet sandarbh par aadharit.',
      'get_guidance': 'Salah Lein (Ask Nabh)',
      'recheck_photo': 'Saaf Photo Dubara Lein',
      'detected_class': 'Detected Class',
      'image_analyzed': 'Image Analyzed',
      'close': 'Band Karein',
      'cancel': 'Cancel',
      'submit': 'Submit',
      'feedback_help': 'NabhKrishi ko behtar banane mein madad karein',
      'feedback_sub': 'Hamari sifarish aapke liye kitni upyogi hai? Apni rai dein.',
      'give_feedback': 'Feedback Dein',
      'feedback_submitted': 'Feedback darj ho gaya!',
      'farmer_feedback': 'Kisan Feedback Form',
      'select_rating': 'Rating Chunein:',
      'comments_optional': 'Comments (optional):',
      'feedback_hint': 'Apna feedback yahan likhein...',
      'weather_modal_title': 'Mausam & Barish Radar',
      'weather_modal_subtitle': 'Field Grid Telemetry',
      'wind_speed': 'Hawa Ki Gati',
      'rain_chance': 'Barish Ki Sambhavna',
      'met_advice_title': 'Krishi Mausam Salah',
      'met_advice_body': 'Agle 48 ghanto mein bhari barish ki sambhavna kam hai. Foliar spray ya scheduled sinchai ki ja sakti hai.',
      'agronomic_advisory_title': 'Fasal Suraksha Salah',
      'agronomic_advisory_subtitle': 'ICAR & University Extension',
      'field_inspection': 'Nigrani & Patti Inspection',
      'field_inspection_desc': 'Rust ya keede ke shuruati lakshano ke liye pattiyon ki regular nigrani karein.',
      'irrigation_mgmt': 'Sinchai Prabandhan',
      'irrigation_mgmt_desc': 'Tillering stage ke dauran khet mein nami banaye rakhein.',
      'bio_mgmt': 'Bachav & Jaivik Upchar',
      'bio_mgmt_desc': 'Subah ke samay Trichoderma ya recommended bio-fungicide ka spray karein.',
      'kvk_helpline': 'KVK Extension Helpline',
      'kvk_helpline_sub': 'Toll-free Agronomist Support: 1800-180-1551',
      'understood': 'Samajh Gaya',
      'days_together': 'Saath mein {days} din 🌱',
      'icar_advisory': 'ICAR Salah',
      'summary_heading': 'Khet & Fasal Health Summary',
      'good_morning': 'Shubh Prabhat',
      'good_afternoon': 'Namaste',
      'good_evening': 'Shubh Sandhya',
      'farmer': 'Kisan Mitra',
      'verified_farmer_account': 'Verified Kisan Account',
      'sign_out_confirm_title': 'Sign Out Karein?',
      'sign_out_confirm_msg': 'Kya aap sach mein apne account se sign out karna chahte hain?',
      'ai_server_lan': 'AI Server Status (LAN)',
      'online': 'Online',
      'offline': 'Offline',
      'latitude_label': 'Latitude',
      'longitude_label': 'Longitude',
      'invalid_lat': 'Invalid Latitude (-90 se 90)',
      'invalid_lng': 'Invalid Longitude (-180 se 180)',
      'locate_farm_coords': 'Khet Location Dhoondhein',
      'point_location': 'Point location (seema nahi banayi)',
      'active_farm_details': 'Active Khet Details',
      'no_saved_farms': 'Koi khet save nahi mila',
      'save_farm_first': 'Analytics data dekhne ke liye pehle home screen par khet chun kar save karein.',
      'insights_trends': 'Fasal Insights & Trends',
      'days_filter_7': '7 Din',
      'days_filter_30': '30 Din',
      'days_filter_all': 'Total Time',
      'swint_vision_result': 'Pehchana Gaya Result (Swin-T)',
      'swint_neural_analysis': 'Patti Analysis Result',
      'wheat_disease_diagnosis': 'Gehun Rog Nidan (Swin-T)',
      'diagnosis': 'Rog Pehchan',
      'ppo_decision': 'Decision',
      'standard_management': 'Standard Management',
      'kvk_consultation': 'Krishi Vigyan Kendra (KVK) ke vaigyaniko se salah lein.',
      'get_verified_guidance': 'Salah Lein (Get Guidance)',
    },
  };

  String translate(String key, {Map<String, String>? arguments}) {
    final langCode = normalizeCode(language);
    String value = _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
    if (arguments != null) {
      arguments.forEach((argKey, val) {
        value = value.replaceAll('{$argKey}', val);
      });
    }
    return value;
  }

  /// Returns localized string by key for any language code or name.
  static String get(String key, [String? lang, Map<String, String>? arguments]) {
    return AppLocalizations(lang ?? 'en').translate(key, arguments: arguments);
  }

  /// Returns localized disease name for any of the 6 languages.
  static String getDiseaseName(String key, [String lang = 'en']) {
    final code = normalizeCode(lang);
    final k = key.toLowerCase().trim();
    return _diseaseTranslations[code]?[k] ?? _diseaseTranslations['en']?[k] ?? key;
  }

  /// Returns localized PPO action name for any of the 6 languages.
  static String getActionName(int actionId, [String lang = 'en', String defaultName = '']) {
    final code = normalizeCode(lang);
    return _ppoActionTranslations[code]?[actionId] ?? _ppoActionTranslations['en']?[actionId] ?? defaultName;
  }

  /// Returns localized status name for any of the 6 languages.
  static String getStatusName(String status, [String lang = 'en']) {
    final code = normalizeCode(lang);
    final s = status.toLowerCase().trim();
    return _statusTranslations[code]?[s] ?? status;
  }

  static const Map<String, Map<String, String>> _diseaseTranslations = {
    'en': {
      'aphid': 'Aphid',
      'black rust': 'Black Rust / Stem Rust',
      'blast': 'Wheat Blast',
      'brown rust': 'Brown Rust / Leaf Rust',
      'common root rot': 'Common Root Rot',
      'fusarium head blight': 'Fusarium Head Blight',
      'healthy': 'Healthy Leaf',
      'leaf blight': 'Leaf Blight',
      'mildew': 'Powdery Mildew',
      'mite': 'Mite',
      'septoria': 'Septoria Leaf Blotch',
      'smut': 'Loose Smut',
      'stem fly': 'Stem Fly',
      'tan spot': 'Tan Spot',
      'yellow rust': 'Yellow Rust / Stripe Rust',
    },
    'hi': {
      'aphid': 'माहू / एफिड (Aphid)',
      'black rust': 'काला रतुआ / तना रतुआ (Black Rust)',
      'blast': 'गेहूं का झुलसा / ब्लास्ट (Blast)',
      'brown rust': 'भूरा रतुआ (Brown Rust)',
      'common root rot': 'जड़ सड़न (Common Root Rot)',
      'fusarium head blight': 'फ्यूजेरियम हेड ब्लाइट (Fusarium Head Blight)',
      'healthy': 'स्वस्थ पत्ती (Healthy)',
      'leaf blight': 'पत्ती झुलसा रोग (Leaf Blight)',
      'mildew': 'चूर्णिल आसिता / पाउडरी मिल्ड्यू (Mildew)',
      'mite': 'मकड़ी / माइट (Mite)',
      'septoria': 'सेप्टोरिया लीफ ब्लॉच (Septoria)',
      'smut': 'कंडुआ रोग / स्मट (Smut)',
      'stem fly': 'तना मक्खी (Stem Fly)',
      'tan spot': 'टैन स्पॉट (Tan Spot)',
      'yellow rust': 'पीला रतुआ (Yellow Rust)',
    },
    'pa': {
      'aphid': 'ਤੇਲਾ / ਚੇਪਾ (Aphid)',
      'black rust': 'ਕਾਲਾ ਰਤੂਆ / ਤਣਾ ਰਤੂਆ (Black Rust)',
      'blast': 'ਕਣਕ ਦਾ ਝੁਲਸਾ / ਬਲਾਸਟ (Blast)',
      'brown rust': 'ਭੂਰਾ ਰਤੂਆ (Brown Rust)',
      'common root rot': 'ਜੜ੍ਹ ਗਲਣ (Common Root Rot)',
      'fusarium head blight': 'ਫਿਊਜ਼ੇਰੀਅਮ ਸਿੱਟਾ ਝੁਲਸਾ (Head Blight)',
      'healthy': 'ਸਿਹਤਮੰਦ ਪੱਤਾ (Healthy)',
      'leaf blight': 'ਪੱਤਾ ਝੁਲਸਾ ਰੋਗ (Leaf Blight)',
      'mildew': 'ਚੂਰਨਿਲ ਉੱਲੀ / ਪਾਊਡਰੀ ਮਿਲਡਿਊ (Mildew)',
      'mite': 'ਜੂੰ / ਮਾਈਟ (Mite)',
      'septoria': 'ਸੈਪਟੋਰੀਆ ਪੱਤਾ ਧੱਬਾ (Septoria)',
      'smut': 'ਕਾਂਗਿਆਰੀ / ਸਮੱਟ (Smut)',
      'stem fly': 'ਤਣਾ ਮੱਖੀ (Stem Fly)',
      'tan spot': 'ਟੈਨ ਸਪੌਟ (Tan Spot)',
      'yellow rust': 'ਪੀਲਾ ਰਤੂਆ / ਕੁੰਗੀ (Yellow Rust)',
    },
    'bn': {
      'aphid': 'জাব পোকা (Aphid)',
      'black rust': 'কালো মরিচা রোগ (Black Rust)',
      'blast': 'গমের ব্লাস্ট রোগ (Wheat Blast)',
      'brown rust': 'বাদামী মরিচা রোগ (Brown Rust)',
      'common root rot': 'শিকড় পচা রোগ (Root Rot)',
      'fusarium head blight': 'ফিউজেরিয়াম হেড ব্লাইট (Head Blight)',
      'healthy': 'সুস্থ পাতা (Healthy)',
      'leaf blight': 'পাতা ঝলসানো রোগ (Leaf Blight)',
      'mildew': 'পাউডারি মিলডিউ (Mildew)',
      'mite': 'মাকড় (Mite)',
      'septoria': 'সেপ্টোরিয়া দাগ (Septoria)',
      'smut': 'আলগা স্মাট / ঝুল রোগ (Smut)',
      'stem fly': 'কাণ্ড মাছি (Stem Fly)',
      'tan spot': 'ট্যান স্পট (Tan Spot)',
      'yellow rust': 'হলুদ মরিচা রোগ (Yellow Rust)',
    },
    'hr': {
      'aphid': 'माहू / चेपा (Aphid)',
      'black rust': 'काळा रतुआ (Black Rust)',
      'blast': 'गेहूं का झुलसा (Blast)',
      'brown rust': 'भूरा रतुआ (Brown Rust)',
      'common root rot': 'जड़ गलन (Root Rot)',
      'fusarium head blight': 'हेड ब्लाइट (Head Blight)',
      'healthy': 'नीरोगी पत्ता (Healthy)',
      'leaf blight': 'पत्ता झुलसा (Leaf Blight)',
      'mildew': 'पाउडरी मिल्ड्यू (Mildew)',
      'mite': 'मकड़ी / माइट (Mite)',
      'septoria': 'सेप्टोरिया चित्ती (Septoria)',
      'smut': 'कंडुआ / कांगियारी (Smut)',
      'stem fly': 'तना माखी (Stem Fly)',
      'tan spot': 'टैन चित्ती (Tan Spot)',
      'yellow rust': 'पीळा रतुआ (Yellow Rust)',
    },
    'hinglish': {
      'aphid': 'Maahu / Aphid',
      'black rust': 'Kaala Ratua (Black Rust)',
      'blast': 'Gehun ka Jhulsa / Blast',
      'brown rust': 'Bhoora Ratua (Brown Rust)',
      'common root rot': 'Jadd Sadhan (Common Root Rot)',
      'fusarium head blight': 'Fusarium Head Blight',
      'healthy': 'Swasth Patti (Healthy)',
      'leaf blight': 'Patti Jhulsa Rog (Leaf Blight)',
      'mildew': 'Powdery Mildew',
      'mite': 'Makdi / Mite',
      'septoria': 'Septoria Leaf Blotch',
      'smut': 'Kandua Rog / Smut',
      'stem fly': 'Tana Makkhi (Stem Fly)',
      'tan spot': 'Tan Spot',
      'yellow rust': 'Peela Ratua (Yellow Rust)',
    },
  };

  static const Map<String, Map<int, String>> _ppoActionTranslations = {
    'en': {
      0: 'Crop Monitoring (Monitor)',
      1: 'Preventive Management (Preventive)',
      2: 'Irrigation / Nutrient Review',
      3: 'Disease Management Review',
      4: 'Capture Clearer Photo (Recheck)',
      5: 'Ask NabhKrishi Chatbot (Ask AI)',
    },
    'hi': {
      0: 'फसल निगरानी (Monitor)',
      1: 'बचाव प्रबंधन समीक्षा (Preventive)',
      2: 'सिंचाई / पोषण समीक्षा (Irrigation/Nutrient)',
      3: 'रोग प्रबंधन समीक्षा (Disease Management)',
      4: 'पुनः जांच (Recheck Photo)',
      5: 'नाभकृषि चैटबॉट से पूछें (Ask AI)',
    },
    'pa': {
      0: 'ਫ਼ਸਲ ਨਿਗਰਾਨੀ (Monitor)',
      1: 'ਬਚਾਅ ਪ੍ਰਬੰਧਨ ਸਮੀਖਿਆ (Preventive)',
      2: 'ਸਿੰਚਾਈ / ਖ਼ੁਰਾਕ ਸਮੀਖਿਆ (Irrigation/Nutrient)',
      3: 'ਰੋਗ ਪ੍ਰਬੰਧਨ ਸਮੀਖਿਆ (Disease Management)',
      4: 'ਦੁਬਾਰਾ ਫੋਟੋ ਲਓ (Recheck Photo)',
      5: 'ਨਾਭਕ੍ਰਿਸ਼ੀ AI ਤੋਂ ਪੁੱਛੋ (Ask AI)',
    },
    'bn': {
      0: 'ফসল পর্যবেক্ষণ (Monitor)',
      1: 'প্রতিরোধমূলক ব্যবস্থা (Preventive)',
      2: 'সেচ ও পুষ্টি পর্যালোচনা (Irrigation/Nutrient)',
      3: 'রোগ ব্যবস্থাপনা পর্যালোচনা (Disease Management)',
      4: 'পুনরায় ছবি তুলুন (Recheck Photo)',
      5: 'নভকৃষি AI-কে জিজ্ঞাসা করুন (Ask AI)',
    },
    'hr': {
      0: 'फसल देखरेख (Monitor)',
      1: 'बचाव जांच (Preventive)',
      2: 'पाणी / खाद पड़ताल (Irrigation/Nutrient)',
      3: 'बीमारी रोकथाम (Disease Management)',
      4: 'दोबारा फोटो खींचो (Recheck Photo)',
      5: 'नभ AI तै पूछो (Ask AI)',
    },
    'hinglish': {
      0: 'Fasal Nigrani (Monitor)',
      1: 'Bachav Prabandhan (Preventive)',
      2: 'Sinchai / Poshan Review',
      3: 'Rog Prabandhan Review',
      4: 'Dobara Photo Lein (Recheck)',
      5: 'NabhKrishi Chatbot se Poochhein (Ask AI)',
    },
  };

  static const Map<String, Map<String, String>> _statusTranslations = {
    'en': {
      'optimal': 'Optimal',
      'good': 'Good',
      'fair': 'Fair',
      'moderate': 'Moderate',
      'alert': 'Alert',
      'critical': 'Critical',
    },
    'hi': {
      'optimal': 'उत्तम (Good)',
      'good': 'उत्तम (Good)',
      'fair': 'मध्यम (Fair)',
      'moderate': 'मध्यम (Fair)',
      'alert': 'सावधानी (Alert)',
      'critical': 'सावधानी (Alert)',
    },
    'pa': {
      'optimal': 'ਵਧੀਆ (Good)',
      'good': 'ਵਧੀਆ (Good)',
      'fair': 'ਦਰਮਿਆਨਾ (Fair)',
      'moderate': 'ਦਰਮਿਆਨਾ (Fair)',
      'alert': 'ਚਿਤਾਵਨੀ (Alert)',
      'critical': 'ਚਿਤਾਵਨੀ (Alert)',
    },
    'bn': {
      'optimal': 'উত্তম (Good)',
      'good': 'উত্তম (Good)',
      'fair': 'মাঝারি (Fair)',
      'moderate': 'মাঝারি (Fair)',
      'alert': 'সতর্কতা (Alert)',
      'critical': 'সতর্কতা (Alert)',
    },
    'hr': {
      'optimal': 'घणा बढ़िया (Good)',
      'good': 'घणा बढ़िया (Good)',
      'fair': 'ठीक-ठाक (Fair)',
      'moderate': 'ठीक-ठाक (Fair)',
      'alert': 'चेत जाओ (Alert)',
      'critical': 'चेत जाओ (Alert)',
    },
    'hinglish': {
      'optimal': 'Uttam (Good)',
      'good': 'Uttam (Good)',
      'fair': 'Madhyam (Fair)',
      'moderate': 'Madhyam (Fair)',
      'alert': 'Savdhani (Alert)',
      'critical': 'Savdhani (Alert)',
    },
  };
}

extension LocalizationExtension on BuildContext {
  AppLocalizations get loc => AppLocalizations('en');

  String translate(String key, String currentLanguage, {Map<String, String>? arguments}) {
    return AppLocalizations.get(key, currentLanguage, arguments);
  }
}

